import { Injectable, Logger } from '@nestjs/common';
import { sql, type RawBuilder, type Transaction } from 'kysely';
import { DatabaseService } from '../../common/database/database.service.js';
import type { Database } from '../../common/database/database.types.js';
import { ApiError } from '../../common/errors/api-error.js';
import { campaignDatabaseError } from './campaign-errors.js';
import type { AssignmentCreate, CampaignList, DeliverableCreate, TransitionInput } from './campaigns.schemas.js';

@Injectable()
export class AdminCampaignsService {
  private readonly logger=new Logger(AdminCampaignsService.name);
  constructor(private readonly database:DatabaseService){}

  list(userId:string,q:CampaignList){return this.database.withUserContext(userId,async(tx)=>{const f:RawBuilder<unknown>[]=[sql`buzzerhood.has_permission('campaigns.read')`];if(q.organizationId)f.push(sql`c.organization_id=${q.organizationId}`);if(q.status)f.push(sql`c.status=${q.status}::buzzerhood.campaign_status_v2`);const where=sql.join(f,sql` and `),offset=(q.page-1)*q.limit;const count=await sql<{total:string}>`select count(*)::text total from buzzerhood.campaigns c where ${where}`.execute(tx);const rows=await sql<{id:string;organization_id:string;organization_name:string;name:string;status:string;estimated_budget:string|null;currency:string;created_at:Date}>`select c.id,c.organization_id,o.name organization_name,c.name,c.status::text,c.estimated_budget::text,c.currency,c.created_at from buzzerhood.campaigns c join buzzerhood.organizations o on o.id=c.organization_id where ${where} order by c.created_at desc limit ${q.limit} offset ${offset}`.execute(tx);const total=Number(count.rows[0]?.total??0);return{data:rows.rows.map(x=>({id:x.id,organizationId:x.organization_id,organizationName:x.organization_name,name:x.name,status:x.status,estimatedBudget:x.estimated_budget===null?null:Number(x.estimated_budget),currency:x.currency.trim(),createdAt:x.created_at})),meta:{page:q.page,limit:q.limit,total,hasNext:offset+rows.rows.length<total}};});}
  detail(userId:string,id:string){return this.database.withUserContext(userId,(tx)=>this.detailTx(tx,id));}
  assignments(userId:string,campaignId:string){return this.database.withUserContext(userId,async(tx)=>{await this.assertCampaign(tx,campaignId);return this.assignmentsTx(tx,campaignId);});}

  async startReview(userId:string,id:string){return this.transition(userId,id,{to:'internal_review'});}
  async approve(userId:string,id:string){return this.transition(userId,id,{to:'planning'});}
  async requestRevision(userId:string,id:string,reason?:string){return this.transition(userId,id,{to:'changes_requested',reason});}
  async transition(userId:string,id:string,input:TransitionInput){try{return await this.database.withUserContext(userId,async(tx)=>{const result=await sql<{status:string}>`select buzzerhood.transition_campaign(${id},${input.to}::buzzerhood.campaign_status_v2,${input.reason??null})::text status`.execute(tx);this.logger.log({event:'campaign.transitioned',actorId:userId,campaignId:id,to:input.to});return{id,status:result.rows[0]?.status};});}catch(error){campaignDatabaseError(error,'CAMPAIGN_NOT_FOUND');}}

  async createAssignment(userId:string,campaignId:string,input:AssignmentCreate){try{return await this.database.withUserContext(userId,async(tx)=>{const result=await sql<{id:string}>`select buzzerhood.invite_campaign_partner(${campaignId},${input.partnerId},${input.agreedFee??null},${input.feeCurrency},${input.rateSnapshot===undefined||input.rateSnapshot===null?null:JSON.stringify(input.rateSnapshot)}::jsonb,${input.internalNotes??null}) id`.execute(tx);const id=result.rows[0]?.id;if(!id)throw new Error('Assignment returned no identifier.');this.logger.log({event:'campaign.assignment.created',actorId:userId,campaignId,assignmentId:id,partnerId:input.partnerId});return this.assignmentTx(tx,id);});}catch(error){campaignDatabaseError(error,'ASSIGNMENT_INVALID_STATE');}}
  async createDeliverable(userId:string,assignmentId:string,input:DeliverableCreate){try{return await this.database.withUserContext(userId,async(tx)=>{const result=await sql<{id:string}>`select buzzerhood.create_campaign_deliverable(${assignmentId},${input.title},${input.description??null},${input.platform??null},${input.dueDate??null}::date,${input.quantity}) id`.execute(tx);const id=result.rows[0]?.id;if(!id)throw new Error('Deliverable returned no identifier.');this.logger.log({event:'campaign.deliverable.created',actorId:userId,assignmentId,deliverableId:id});return this.deliverableTx(tx,id);});}catch(error){campaignDatabaseError(error,'DELIVERABLE_NOT_FOUND');}}
  async reviewContent(userId:string,submissionId:string,decision:'approved'|'revision_requested',note?:string){try{return await this.database.withUserContext(userId,async(tx)=>{await sql`select buzzerhood.review_content_submission(${submissionId},'internal'::buzzerhood.content_review_context,${decision}::buzzerhood.content_review_decision,${note??null})`.execute(tx);this.logger.log({event:`content.internal.${decision}`,actorId:userId,submissionId});return{id:submissionId,decision};});}catch(error){campaignDatabaseError(error,'CONTENT_REVIEW_NOT_ALLOWED');}}
  async verifyPublication(userId:string,publicationId:string,decision:'verified'|'rejected',note?:string){try{return await this.database.withUserContext(userId,async(tx)=>{const result=await sql<{status:string}>`select buzzerhood.verify_publication(${publicationId},${decision}::buzzerhood.publication_status,${note??null})::text status`.execute(tx);this.logger.log({event:`publication.${decision}`,actorId:userId,publicationId});return{id:publicationId,status:result.rows[0]?.status};});}catch(error){campaignDatabaseError(error,'PUBLICATION_NOT_ALLOWED');}}

  private async assertCampaign(tx:Transaction<Database>,id:string){const r=await sql<{id:string}>`select id from buzzerhood.campaigns where id=${id} and buzzerhood.has_permission('campaigns.read')`.execute(tx);if(!r.rows[0])throw new ApiError(404,'CAMPAIGN_NOT_FOUND','Campaign tidak ditemukan.');}
  private async detailTx(tx:Transaction<Database>,id:string){await this.assertCampaign(tx,id);const c=await sql<{id:string;organization_id:string;organization_name:string;name:string;reference_code:string|null;status:string;objective_summary:string|null;planned_start:string|null;planned_end:string|null;estimated_budget:string|null;currency:string;created_by:string;submitted_at:Date|null;completed_at:Date|null;created_at:Date;updated_at:Date}>`select c.id,c.organization_id,o.name organization_name,c.name,c.reference_code,c.status::text,c.objective_summary,c.planned_start::text,c.planned_end::text,c.estimated_budget::text,c.currency,c.created_by,c.submitted_at,c.completed_at,c.created_at,c.updated_at from buzzerhood.campaigns c join buzzerhood.organizations o on o.id=c.organization_id where c.id=${id}`.execute(tx);const b=await sql<{objective:string|null;description:string|null;target_audience:string|null;key_message:string|null;call_to_action:string|null;content_direction:string|null;prohibited_content:string|null;notes:string|null;kpi_expectation:string|null;context:unknown}>`select objective,description,target_audience,key_message,call_to_action,content_direction,prohibited_content,notes,kpi_expectation,context from buzzerhood.campaign_briefs where campaign_id=${id}`.execute(tx);const x=c.rows[0]!;return{id:x.id,organizationId:x.organization_id,organizationName:x.organization_name,name:x.name,referenceCode:x.reference_code,status:x.status,objectiveSummary:x.objective_summary,plannedStart:x.planned_start,plannedEnd:x.planned_end,estimatedBudget:x.estimated_budget===null?null:Number(x.estimated_budget),currency:x.currency.trim(),createdBy:x.created_by,submittedAt:x.submitted_at,completedAt:x.completed_at,createdAt:x.created_at,updatedAt:x.updated_at,brief:b.rows[0]?{objective:b.rows[0].objective,description:b.rows[0].description,targetAudience:b.rows[0].target_audience,keyMessage:b.rows[0].key_message,callToAction:b.rows[0].call_to_action,contentDirection:b.rows[0].content_direction,prohibitedContent:b.rows[0].prohibited_content,notes:b.rows[0].notes,kpiExpectation:b.rows[0].kpi_expectation,context:b.rows[0].context}:null,assignments:await this.assignmentsTx(tx,id)};}
  private async assignmentsTx(tx:Transaction<Database>,campaignId:string){const r=await sql<{id:string;campaign_id:string;partner_id:string;partner_name:string;status:string;invited_at:Date;responded_at:Date|null;accepted_at:Date|null;agreed_fee:string|null;fee_currency:string|null;rate_snapshot:unknown;internal_notes:string|null}>`select a.id,a.campaign_id,a.partner_id,p.display_name partner_name,a.status::text,a.invited_at,a.responded_at,a.accepted_at,a.agreed_fee::text,a.fee_currency,a.rate_snapshot,a.internal_notes from buzzerhood.campaign_partner_assignments a join buzzerhood.partners p on p.id=a.partner_id where a.campaign_id=${campaignId} order by a.invited_at`.execute(tx);return r.rows.map(x=>({id:x.id,campaignId:x.campaign_id,partnerId:x.partner_id,partnerDisplayName:x.partner_name,status:x.status,invitedAt:x.invited_at,respondedAt:x.responded_at,acceptedAt:x.accepted_at,agreedFee:x.agreed_fee===null?null:Number(x.agreed_fee),feeCurrency:x.fee_currency?.trim()??null,rateSnapshot:x.rate_snapshot,internalNotes:x.internal_notes}));}
  private async assignmentTx(tx:Transaction<Database>,id:string){const r=await sql<{id:string;campaign_id:string;partner_id:string;status:string;agreed_fee:string|null;fee_currency:string|null;rate_snapshot:unknown;internal_notes:string|null}>`select id,campaign_id,partner_id,status::text,agreed_fee::text,fee_currency,rate_snapshot,internal_notes from buzzerhood.campaign_partner_assignments where id=${id}`.execute(tx);const x=r.rows[0];if(!x)throw new ApiError(404,'ASSIGNMENT_NOT_FOUND','Assignment tidak ditemukan.');return{id:x.id,campaignId:x.campaign_id,partnerId:x.partner_id,status:x.status,agreedFee:x.agreed_fee===null?null:Number(x.agreed_fee),feeCurrency:x.fee_currency?.trim()??null,rateSnapshot:x.rate_snapshot,internalNotes:x.internal_notes};}
  private async deliverableTx(tx:Transaction<Database>,id:string){const r=await sql<{id:string;assignment_id:string;title:string;description:string|null;platform:string|null;due_date:string|null;quantity:number;status:string}>`select id,assignment_id,title,description,platform,due_date::text,quantity,status::text from buzzerhood.campaign_deliverables where id=${id}`.execute(tx);const x=r.rows[0];if(!x)throw new ApiError(404,'DELIVERABLE_NOT_FOUND','Deliverable tidak ditemukan.');return{id:x.id,assignmentId:x.assignment_id,title:x.title,description:x.description,platform:x.platform,dueDate:x.due_date,quantity:x.quantity,status:x.status};}
}
