import { Injectable, Logger } from '@nestjs/common';
import { sql, type Transaction } from 'kysely';
import { DatabaseService } from '../../common/database/database.service.js';
import type { Database } from '../../common/database/database.types.js';
import { ApiError } from '../../common/errors/api-error.js';
import { campaignDatabaseError } from './campaign-errors.js';
import type { MetricCreate, PublicationCreate, SubmissionCreate } from './campaigns.schemas.js';

@Injectable()
export class CampaignExecutionService {
  private readonly logger=new Logger(CampaignExecutionService.name);
  constructor(private readonly database:DatabaseService){}

  listMine(userId:string){return this.database.withUserContext(userId,async(tx)=>{const r=await sql<{id:string;campaign_id:string;partner_id:string;campaign_name:string;status:string;invited_at:Date;responded_at:Date|null;accepted_at:Date|null;agreed_fee:string|null;fee_currency:string|null}>`select a.id,a.campaign_id,a.partner_id,c.name campaign_name,a.status::text,a.invited_at,a.responded_at,a.accepted_at,a.agreed_fee::text,a.fee_currency from buzzerhood.campaign_partner_assignments a join buzzerhood.campaigns c on c.id=a.campaign_id where buzzerhood.is_active_partner_member(a.partner_id) order by a.invited_at desc`.execute(tx);return r.rows.map(x=>this.partnerAssignmentDto(x));});}
  getAssignment(userId:string,id:string){return this.database.withUserContext(userId,async(tx)=>{await this.assertExecutionAssignment(tx,id);const a=await sql<{id:string;campaign_id:string;partner_id:string;campaign_name:string;status:string;invited_at:Date;responded_at:Date|null;accepted_at:Date|null;agreed_fee:string|null;fee_currency:string|null}>`select a.id,a.campaign_id,a.partner_id,c.name campaign_name,a.status::text,a.invited_at,a.responded_at,a.accepted_at,a.agreed_fee::text,a.fee_currency from buzzerhood.campaign_partner_assignments a join buzzerhood.campaigns c on c.id=a.campaign_id where a.id=${id}`.execute(tx);const x=a.rows[0];if(!x)throw new ApiError(404,'ASSIGNMENT_NOT_FOUND','Assignment tidak ditemukan.');const brief=await sql<{objective:string|null;description:string|null;target_audience:string|null;key_message:string|null;call_to_action:string|null;content_direction:string|null}>`select b.objective,b.description,b.target_audience,b.key_message,b.call_to_action,b.content_direction from buzzerhood.campaign_briefs b join buzzerhood.campaign_partner_assignments a on a.campaign_id=b.campaign_id where a.id=${id}`.execute(tx);return{...this.partnerAssignmentDto(x),brief:brief.rows[0]?{objective:brief.rows[0].objective,description:brief.rows[0].description,targetAudience:brief.rows[0].target_audience,keyMessage:brief.rows[0].key_message,callToAction:brief.rows[0].call_to_action,contentDirection:brief.rows[0].content_direction}:null,deliverables:await this.deliverablesTx(tx,id)};});}

  async respond(userId:string,id:string,response:'accepted'|'declined',reason?:string){try{return await this.database.withUserContext(userId,async(tx)=>{const r=await sql<{status:string}>`select buzzerhood.respond_campaign_assignment(${id},${response},${reason??null})::text status`.execute(tx);this.logger.log({event:`campaign.assignment.${response}`,actorId:userId,assignmentId:id});return{id,status:r.rows[0]?.status};});}catch(error){campaignDatabaseError(error,'ASSIGNMENT_NOT_FOUND');}}
  deliverables(userId:string,assignmentId:string){return this.database.withUserContext(userId,async(tx)=>{const visible=await sql<{allowed:boolean}>`select buzzerhood.campaign_assignment_visible(${assignmentId}) allowed`.execute(tx);if(visible.rows[0]?.allowed!==true)throw new ApiError(404,'ASSIGNMENT_NOT_FOUND','Assignment tidak ditemukan.');return this.deliverablesTx(tx,assignmentId);});}

  submissions(userId:string,deliverableId:string){return this.database.withUserContext(userId,async(tx)=>{await this.assertDeliverable(tx,deliverableId);return this.submissionsTx(tx,deliverableId);});}
  async submitContent(userId:string,deliverableId:string,input:SubmissionCreate){try{return await this.database.withUserContext(userId,async(tx)=>{const r=await sql<{id:string}>`select buzzerhood.submit_content_version(${deliverableId},${input.captionBody},${input.conceptNotes??null},${input.assetReference??null},${input.contentUrl??null}) id`.execute(tx);const id=r.rows[0]?.id;if(!id)throw new Error('Submission returned no identifier.');this.logger.log({event:'content.submitted',actorId:userId,deliverableId,submissionId:id});const rows=await this.submissionsTx(tx,deliverableId);return rows.find(x=>x.id===id)??{id};});}catch(error){campaignDatabaseError(error,'DELIVERABLE_NOT_FOUND');}}
  async clientReview(userId:string,submissionId:string,decision:'approved'|'revision_requested',note?:string){try{return await this.database.withUserContext(userId,async(tx)=>{await sql`select buzzerhood.review_content_submission(${submissionId},'client'::buzzerhood.content_review_context,${decision}::buzzerhood.content_review_decision,${note??null})`.execute(tx);this.logger.log({event:`content.client.${decision}`,actorId:userId,submissionId});return{id:submissionId,decision};});}catch(error){campaignDatabaseError(error,'CONTENT_REVIEW_NOT_ALLOWED');}}

  async publish(userId:string,deliverableId:string,input:PublicationCreate){try{return await this.database.withUserContext(userId,async(tx)=>{const r=await sql<{id:string}>`select buzzerhood.submit_publication(${deliverableId},${input.submissionId},${input.publicationUrl},${input.platformAccountId??null}) id`.execute(tx);const id=r.rows[0]?.id;if(!id)throw new Error('Publication returned no identifier.');this.logger.log({event:'publication.submitted',actorId:userId,deliverableId,publicationId:id});return this.publicationTx(tx,id);});}catch(error){campaignDatabaseError(error,'PUBLICATION_NOT_ALLOWED');}}
  metrics(userId:string,publicationId:string){return this.database.withUserContext(userId,async(tx)=>{await this.assertPublication(tx,publicationId);const r=await sql<{id:string;metric_type:string;metric_value:string;period_start:string|null;period_end:string|null;source:string;captured_at:Date}>`select id,metric_type::text,metric_value::text,period_start::text,period_end::text,source,captured_at from buzzerhood.publication_metric_snapshots where publication_id=${publicationId} order by captured_at desc`.execute(tx);return r.rows.map(x=>({id:x.id,metricType:x.metric_type,metricValue:Number(x.metric_value),periodStart:x.period_start,periodEnd:x.period_end,source:x.source,capturedAt:x.captured_at}));});}
  async recordMetric(userId:string,publicationId:string,input:MetricCreate){try{return await this.database.withUserContext(userId,async(tx)=>{const r=await sql<{id:string}>`select buzzerhood.record_publication_metric(${publicationId},${input.metricType}::buzzerhood.metric_type,${input.metricValue},${input.source},${input.periodStart??null}::date,${input.periodEnd??null}::date,${input.note??null}) id`.execute(tx);const id=r.rows[0]?.id;if(!id)throw new Error('Metric returned no identifier.');this.logger.log({event:'publication.metric.recorded',actorId:userId,publicationId,metricId:id,metricType:input.metricType});const rows=await sql<{id:string;metric_type:string;metric_value:string;period_start:string|null;period_end:string|null;source:string;captured_at:Date}>`select id,metric_type::text,metric_value::text,period_start::text,period_end::text,source,captured_at from buzzerhood.publication_metric_snapshots where id=${id}`.execute(tx);const x=rows.rows[0]!;return{id:x.id,metricType:x.metric_type,metricValue:Number(x.metric_value),periodStart:x.period_start,periodEnd:x.period_end,source:x.source,capturedAt:x.captured_at};});}catch(error){campaignDatabaseError(error,'METRIC_NOT_ALLOWED');}}

  private async assertExecutionAssignment(tx:Transaction<Database>,id:string){const r=await sql<{allowed:boolean}>`select (buzzerhood.has_permission('campaigns.read') or exists(select 1 from buzzerhood.campaign_partner_assignments a where a.id=${id} and buzzerhood.is_active_partner_member(a.partner_id))) allowed`.execute(tx);if(r.rows[0]?.allowed!==true)throw new ApiError(404,'ASSIGNMENT_NOT_FOUND','Assignment tidak ditemukan.');}
  private async assertDeliverable(tx:Transaction<Database>,id:string){const r=await sql<{allowed:boolean}>`select buzzerhood.campaign_deliverable_visible(${id}) allowed`.execute(tx);if(r.rows[0]?.allowed!==true)throw new ApiError(404,'DELIVERABLE_NOT_FOUND','Deliverable tidak ditemukan.');}
  private async assertPublication(tx:Transaction<Database>,id:string){const r=await sql<{allowed:boolean}>`select buzzerhood.campaign_publication_visible(${id}) allowed`.execute(tx);if(r.rows[0]?.allowed!==true)throw new ApiError(404,'PUBLICATION_NOT_FOUND','Publication tidak ditemukan.');}
  private async deliverablesTx(tx:Transaction<Database>,assignmentId:string){const r=await sql<{id:string;assignment_id:string;title:string;description:string|null;platform:string|null;due_date:string|null;quantity:number;status:string;created_at:Date;updated_at:Date}>`select id,assignment_id,title,description,platform,due_date::text,quantity,status::text,created_at,updated_at from buzzerhood.campaign_deliverables where assignment_id=${assignmentId} order by created_at`.execute(tx);return r.rows.map(x=>({id:x.id,assignmentId:x.assignment_id,title:x.title,description:x.description,platform:x.platform,dueDate:x.due_date,quantity:x.quantity,status:x.status,createdAt:x.created_at,updatedAt:x.updated_at}));}
  private async submissionsTx(tx:Transaction<Database>,deliverableId:string){const r=await sql<{id:string;deliverable_id:string;version:number;status:string;caption_body:string|null;concept_notes:string|null;asset_reference:string|null;content_url:string|null;submitted_at:Date}>`select id,deliverable_id,version,status::text,caption_body,concept_notes,asset_reference,content_url,submitted_at from buzzerhood.content_submissions where deliverable_id=${deliverableId} order by version`.execute(tx);return r.rows.map(x=>({id:x.id,deliverableId:x.deliverable_id,version:x.version,status:x.status,captionBody:x.caption_body,conceptNotes:x.concept_notes,assetReference:x.asset_reference,contentUrl:x.content_url,submittedAt:x.submitted_at}));}
  private async publicationTx(tx:Transaction<Database>,id:string){const r=await sql<{id:string;deliverable_id:string;content_submission_id:string;platform_account_id:string|null;publication_url:string;status:string;submitted_at:Date;verified_at:Date|null}>`select id,deliverable_id,content_submission_id,platform_account_id,publication_url,status::text,submitted_at,verified_at from buzzerhood.publications where id=${id}`.execute(tx);const x=r.rows[0];if(!x)throw new ApiError(404,'PUBLICATION_NOT_FOUND','Publication tidak ditemukan.');return{id:x.id,deliverableId:x.deliverable_id,submissionId:x.content_submission_id,platformAccountId:x.platform_account_id,publicationUrl:x.publication_url,status:x.status,submittedAt:x.submitted_at,verifiedAt:x.verified_at};}
  private partnerAssignmentDto(x:{id:string;campaign_id:string;partner_id:string;campaign_name:string;status:string;invited_at:Date;responded_at:Date|null;accepted_at:Date|null;agreed_fee:string|null;fee_currency:string|null}){return{id:x.id,campaignId:x.campaign_id,partnerId:x.partner_id,campaignName:x.campaign_name,status:x.status,invitedAt:x.invited_at,respondedAt:x.responded_at,acceptedAt:x.accepted_at,agreedFee:x.agreed_fee===null?null:Number(x.agreed_fee),feeCurrency:x.fee_currency?.trim()??null};}
}
