import { Injectable, Logger } from '@nestjs/common';
import { sql, type RawBuilder, type Transaction } from 'kysely';
import { DatabaseService } from '../../common/database/database.service.js';
import type { Database } from '../../common/database/database.types.js';
import { ApiError } from '../../common/errors/api-error.js';
import { campaignDatabaseError } from './campaign-errors.js';
import type { CampaignList, CreateCampaign, UpdateCampaign } from './campaigns.schemas.js';

type CampaignRow = { id:string;organization_id:string;organization_name:string;name:string;reference_code:string|null;status:string;objective_summary:string|null;planned_start:string|null;planned_end:string|null;estimated_budget:string|null;currency:string;submitted_at:Date|null;completed_at:Date|null;created_at:Date;updated_at:Date };
type BriefRow = { campaign_id:string;objective:string|null;description:string|null;target_audience:string|null;key_message:string|null;call_to_action:string|null;content_direction:string|null;prohibited_content:string|null;notes:string|null;kpi_expectation:string|null;context:unknown;updated_at:Date };

@Injectable()
export class CampaignsService {
  private readonly logger = new Logger(CampaignsService.name);
  constructor(private readonly database: DatabaseService) {}

  list(userId:string, query:CampaignList) { return this.database.withUserContext(userId, async (tx) => {
    const filters:RawBuilder<unknown>[]=[sql`buzzerhood.is_active_organization_member(c.organization_id)`];
    if(query.organizationId)filters.push(sql`c.organization_id=${query.organizationId}`);
    if(query.status)filters.push(sql`c.status=${query.status}::buzzerhood.campaign_status_v2`);
    const where=sql.join(filters,sql` and `),offset=(query.page-1)*query.limit;
    const count=await sql<{total:string}>`select count(*)::text total from buzzerhood.campaigns c where ${where}`.execute(tx);
    const rows=await sql<CampaignRow>`select c.id,c.organization_id,o.name organization_name,c.name,c.reference_code,c.status::text,c.objective_summary,c.planned_start::text,c.planned_end::text,c.estimated_budget::text,c.currency,c.submitted_at,c.completed_at,c.created_at,c.updated_at from buzzerhood.campaigns c join buzzerhood.organizations o on o.id=c.organization_id where ${where} order by c.created_at desc limit ${query.limit} offset ${offset}`.execute(tx);
    const total=Number(count.rows[0]?.total??0);return{data:rows.rows.map((row)=>this.clientDto(row)),meta:{page:query.page,limit:query.limit,total,hasNext:offset+rows.rows.length<total}};
  }); }

  async create(userId:string,input:CreateCampaign){try{return await this.database.withUserContext(userId,async(tx)=>{const result=await sql<{id:string}>`select buzzerhood.create_campaign(${input.organizationId},${input.name},${input.objectiveSummary??null}) id`.execute(tx);const id=result.rows[0]?.id;if(!id)throw new Error('Campaign creation returned no identifier.');this.logger.log({event:'campaign.created',actorId:userId,campaignId:id,organizationId:input.organizationId});return this.getClientTx(tx,id);});}catch(error){campaignDatabaseError(error,'CAMPAIGN_NOT_FOUND');}}
  get(userId:string,id:string){return this.database.withUserContext(userId,(tx)=>this.getClientTx(tx,id));}

  async update(userId:string,id:string,input:UpdateCampaign){try{return await this.database.withUserContext(userId,async(tx)=>{
    const visible=await sql<{id:string}>`select id from buzzerhood.campaigns where id=${id} and buzzerhood.is_active_organization_member(organization_id) and status in ('draft','changes_requested')`.execute(tx);if(!visible.rows[0])throw new ApiError(404,'CAMPAIGN_NOT_FOUND','Campaign tidak ditemukan atau tidak dapat diedit.');
    await sql`update buzzerhood.campaigns set name=case when ${input.name!==undefined} then ${input.name??null} else name end,objective_summary=case when ${input.objectiveSummary!==undefined} then ${input.objectiveSummary??null} else objective_summary end,planned_start=case when ${input.plannedStart!==undefined} then ${input.plannedStart??null}::date else planned_start end,planned_end=case when ${input.plannedEnd!==undefined} then ${input.plannedEnd??null}::date else planned_end end,estimated_budget=case when ${input.estimatedBudget!==undefined} then ${input.estimatedBudget??null}::numeric else estimated_budget end,currency=case when ${input.currency!==undefined} then ${input.currency??null} else currency end,updated_at=now() where id=${id}`.execute(tx);
    if(input.brief){const b=input.brief;await sql`update buzzerhood.campaign_briefs set objective=case when ${b.objective!==undefined} then ${b.objective??null} else objective end,description=case when ${b.description!==undefined} then ${b.description??null} else description end,target_audience=case when ${b.targetAudience!==undefined} then ${b.targetAudience??null} else target_audience end,key_message=case when ${b.keyMessage!==undefined} then ${b.keyMessage??null} else key_message end,call_to_action=case when ${b.callToAction!==undefined} then ${b.callToAction??null} else call_to_action end,content_direction=case when ${b.contentDirection!==undefined} then ${b.contentDirection??null} else content_direction end,prohibited_content=case when ${b.prohibitedContent!==undefined} then ${b.prohibitedContent??null} else prohibited_content end,notes=case when ${b.notes!==undefined} then ${b.notes??null} else notes end,kpi_expectation=case when ${b.kpiExpectation!==undefined} then ${b.kpiExpectation??null} else kpi_expectation end,context=case when ${b.context!==undefined} then ${b.context===null?null:JSON.stringify(b.context)}::jsonb else context end,updated_at=now() where campaign_id=${id}`.execute(tx);}
    this.logger.log({event:'campaign.updated',actorId:userId,campaignId:id});return this.getClientTx(tx,id);
  });}catch(error){campaignDatabaseError(error,'CAMPAIGN_NOT_FOUND');}}

  async submit(userId:string,id:string){try{return await this.database.withUserContext(userId,async(tx)=>{const current=await sql<{status:string}>`select status::text from buzzerhood.campaigns where id=${id} and buzzerhood.is_active_organization_member(organization_id)`.execute(tx);if(!current.rows[0])throw new ApiError(404,'CAMPAIGN_NOT_FOUND','Campaign tidak ditemukan.');if(current.rows[0].status==='changes_requested')await sql`select buzzerhood.transition_campaign(${id},'draft',null)`.execute(tx);const result=await sql<{status:string}>`select buzzerhood.transition_campaign(${id},'submitted',null)::text status`.execute(tx);this.logger.log({event:'campaign.submitted',actorId:userId,campaignId:id});return{id,status:result.rows[0]?.status};});}catch(error){campaignDatabaseError(error,'CAMPAIGN_NOT_FOUND');}}

  private async getClientTx(tx:Transaction<Database>,id:string){const campaign=await sql<CampaignRow>`select c.id,c.organization_id,o.name organization_name,c.name,c.reference_code,c.status::text,c.objective_summary,c.planned_start::text,c.planned_end::text,c.estimated_budget::text,c.currency,c.submitted_at,c.completed_at,c.created_at,c.updated_at from buzzerhood.campaigns c join buzzerhood.organizations o on o.id=c.organization_id where c.id=${id} and buzzerhood.is_active_organization_member(c.organization_id)`.execute(tx);const row=campaign.rows[0];if(!row)throw new ApiError(404,'CAMPAIGN_NOT_FOUND','Campaign tidak ditemukan.');const brief=await sql<BriefRow>`select campaign_id,objective,description,target_audience,key_message,call_to_action,content_direction,prohibited_content,notes,kpi_expectation,context,updated_at from buzzerhood.campaign_briefs where campaign_id=${id}`.execute(tx);const assignments=await sql<{id:string;partner_id:string;partner_name:string;status:string;invited_at:Date;responded_at:Date|null;accepted_at:Date|null}>`select a.id,a.partner_id,p.display_name partner_name,a.status::text,a.invited_at,a.responded_at,a.accepted_at from buzzerhood.campaign_partner_assignments a join buzzerhood.partners p on p.id=a.partner_id where a.campaign_id=${id} order by a.invited_at`.execute(tx);return{...this.clientDto(row),brief:brief.rows[0]?this.briefDto(brief.rows[0]):null,assignments:assignments.rows.map(a=>({id:a.id,partnerId:a.partner_id,partnerDisplayName:a.partner_name,status:a.status,invitedAt:a.invited_at,respondedAt:a.responded_at,acceptedAt:a.accepted_at}))};}
  private clientDto(row:CampaignRow){return{id:row.id,organizationId:row.organization_id,organizationName:row.organization_name,name:row.name,referenceCode:row.reference_code,status:row.status,objectiveSummary:row.objective_summary,plannedStart:row.planned_start,plannedEnd:row.planned_end,estimatedBudget:row.estimated_budget===null?null:Number(row.estimated_budget),currency:row.currency.trim(),submittedAt:row.submitted_at,completedAt:row.completed_at,createdAt:row.created_at,updatedAt:row.updated_at};}
  private briefDto(row:BriefRow){return{objective:row.objective,description:row.description,targetAudience:row.target_audience,keyMessage:row.key_message,callToAction:row.call_to_action,contentDirection:row.content_direction,prohibitedContent:row.prohibited_content,notes:row.notes,kpiExpectation:row.kpi_expectation,context:row.context,updatedAt:row.updated_at};}
}
