import{Injectable,Logger}from'@nestjs/common';import{sql,type Transaction}from'kysely';
import{DatabaseService}from'../../common/database/database.service.js';import type{Database}from'../../common/database/database.types.js';import{ApiError}from'../../common/errors/api-error.js';import{conflictFromDatabase}from'../../common/errors/postgres-error.js';import type{PartnerUpdate,PlatformCreate,PlatformUpdate,RateCreate,RateUpdate}from'./partners.schemas.js';

type PartnerRow={id:string;display_name:string;partner_kind:string;legal_name:string|null;partner_type:string|null;tier:string|null;category:string|null;niche:string|null;location:string|null;bio:string|null;verification_status:string;is_public:boolean};
@Injectable()export class PartnersService{
 private readonly logger=new Logger(PartnersService.name);constructor(private readonly database:DatabaseService){}
 listMine(userId:string){return this.database.withUserContext(userId,async tx=>{const r=await sql<PartnerRow&{role:string}>`select p.id,p.display_name,p.partner_kind,p.legal_name,p.partner_type,p.tier,p.category,p.niche,p.location,p.bio,p.verification_status,p.is_public,m.role::text role from buzzerhood.partner_members m join buzzerhood.partners p on p.id=m.partner_id where m.profile_id=${userId} and m.status='active' order by p.display_name`.execute(tx);return r.rows.map(x=>({...this.dto(x),membershipRole:x.role}));});}
 get(userId:string,id:string){return this.database.withUserContext(userId,async tx=>{await this.ensureRead(tx,id);return this.getTx(tx,id);});}
 async update(userId:string,id:string,input:PartnerUpdate){return this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,id);const r=await sql<{id:string}>`update buzzerhood.partners set display_name=coalesce(${input.displayName??null},display_name),legal_name=case when ${input.legalName===undefined} then legal_name else ${input.legalName??null} end,partner_type=case when ${input.partnerType===undefined} then partner_type else ${input.partnerType??null} end,category=case when ${input.category===undefined} then category else ${input.category??null} end,niche=case when ${input.niche===undefined} then niche else ${input.niche??null} end,location=case when ${input.location===undefined} then location else ${input.location??null} end,bio=case when ${input.bio===undefined} then bio else ${input.bio??null} end,updated_at=now() where id=${id} returning id`.execute(tx);if(!r.rows[0])this.notFound();this.logger.log({event:'partner.updated',actorId:userId,partnerId:id});return this.getTx(tx,id);});}
 platforms(userId:string,id:string){return this.database.withUserContext(userId,async tx=>{await this.ensureRead(tx,id);const r=await sql<{id:string;platform:string;handle:string|null;profile_url:string|null;is_primary:boolean;created_at:Date;updated_at:Date}>`select id,platform,handle,profile_url,is_primary,created_at,updated_at from buzzerhood.partner_platform_accounts where partner_id=${id} order by is_primary desc,created_at`.execute(tx);return r.rows.map(x=>({id:x.id,platform:x.platform,handle:x.handle,profileUrl:x.profile_url,isPrimary:x.is_primary,createdAt:x.created_at,updatedAt:x.updated_at}));});}
 async createPlatform(userId:string,partnerId:string,input:PlatformCreate){try{return await this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);if(input.isPrimary)await sql`update buzzerhood.partner_platform_accounts set is_primary=false,updated_at=now() where partner_id=${partnerId} and is_primary=true`.execute(tx);const r=await sql<{id:string}>`insert into buzzerhood.partner_platform_accounts(partner_id,platform,handle,profile_url,is_primary) values(${partnerId},${input.platform},${input.handle??null},${input.profileUrl??null},${input.isPrimary}) returning id`.execute(tx);this.logger.log({event:'partner.platform.created',actorId:userId,partnerId,platformId:r.rows[0]?.id});return(this.platformsTx(tx,partnerId,r.rows[0]?.id??''));});}catch(e){conflictFromDatabase(e,'PARTNER_PLATFORM_CONFLICT','Akun platform tersebut sudah ada.');}}
 async updatePlatform(userId:string,partnerId:string,platformId:string,input:PlatformUpdate){try{return await this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);if(input.isPrimary===true)await sql`update buzzerhood.partner_platform_accounts set is_primary=false,updated_at=now() where partner_id=${partnerId} and id<>${platformId} and is_primary=true`.execute(tx);const r=await sql<{id:string}>`update buzzerhood.partner_platform_accounts set platform=coalesce(${input.platform??null},platform),handle=case when ${input.handle===undefined} then handle else ${input.handle??null} end,profile_url=case when ${input.profileUrl===undefined} then profile_url else ${input.profileUrl??null} end,is_primary=coalesce(${input.isPrimary??null},is_primary),updated_at=now() where id=${platformId} and partner_id=${partnerId} returning id`.execute(tx);if(!r.rows[0])throw new ApiError(404,'PARTNER_PLATFORM_NOT_FOUND','Akun platform tidak ditemukan.');this.logger.log({event:'partner.platform.updated',actorId:userId,partnerId,platformId});return this.platformsTx(tx,partnerId,platformId);});}catch(e){if(e instanceof ApiError)throw e;conflictFromDatabase(e,'PARTNER_PLATFORM_CONFLICT','Akun platform tersebut sudah ada.');}}
 deletePlatform(userId:string,partnerId:string,platformId:string){return this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);const r=await sql<{id:string}>`delete from buzzerhood.partner_platform_accounts where id=${platformId} and partner_id=${partnerId} returning id`.execute(tx);if(!r.rows[0])throw new ApiError(404,'PARTNER_PLATFORM_NOT_FOUND','Akun platform tidak ditemukan.');this.logger.log({event:'partner.platform.deleted',actorId:userId,partnerId,platformId});return{success:true};});}
 metrics(userId:string,partnerId:string){return this.database.withUserContext(userId,async tx=>{await this.ensureRead(tx,partnerId);const r=await sql<{id:string;platform_account_id:string;platform:string;handle:string|null;metric_type:string;metric_value:string;period_start:string|null;period_end:string|null;observed_at:Date;metric_source:string}>`select m.id,m.platform_account_id,a.platform,a.handle,m.metric_type::text,m.metric_value::text,m.period_start::text,m.period_end::text,m.observed_at,m.metric_source from buzzerhood.partner_audience_metrics m join buzzerhood.partner_platform_accounts a on a.id=m.platform_account_id where a.partner_id=${partnerId} order by m.observed_at desc`.execute(tx);return r.rows.map(x=>({id:x.id,platformAccountId:x.platform_account_id,platform:x.platform,handle:x.handle,metricType:x.metric_type,metricValue:Number(x.metric_value),periodStart:x.period_start,periodEnd:x.period_end,observedAt:x.observed_at,source:x.metric_source}));});}
 rates(userId:string,partnerId:string){return this.database.withUserContext(userId,async tx=>{await this.ensureRead(tx,partnerId);const r=await sql<{id:string;service_type:string;amount:string;currency:string;effective_from:string;effective_to:string|null;is_active:boolean;created_at:Date}>`select id,service_type,amount::text,currency,effective_from::text,effective_to::text,is_active,created_at from buzzerhood.partner_rates where partner_id=${partnerId} order by created_at desc`.execute(tx);return r.rows.map(x=>this.rateDto(x));});}
 async createRate(userId:string,partnerId:string,input:RateCreate){return this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);const r=await sql<{id:string}>`insert into buzzerhood.partner_rates(partner_id,service_type,amount,currency,effective_from) values(${partnerId},${input.serviceType},${input.amount},${input.currency},coalesce(${input.effectiveFrom??null}::date,current_date)) returning id`.execute(tx);this.logger.log({event:'partner.rate.created',actorId:userId,partnerId,rateId:r.rows[0]?.id});return this.rateTx(tx,partnerId,r.rows[0]?.id??'');});}
 async updateRate(userId:string,partnerId:string,rateId:string,input:RateUpdate){return this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);const r=await sql<{id:string}>`update buzzerhood.partner_rates set service_type=coalesce(${input.serviceType??null},service_type),amount=coalesce(${input.amount??null},amount),currency=coalesce(${input.currency??null},currency),effective_from=coalesce(${input.effectiveFrom??null}::date,effective_from) where id=${rateId} and partner_id=${partnerId} returning id`.execute(tx);if(!r.rows[0])throw new ApiError(404,'PARTNER_RATE_NOT_FOUND','Rate tidak ditemukan.');this.logger.log({event:'partner.rate.updated',actorId:userId,partnerId,rateId});return this.rateTx(tx,partnerId,rateId);});}
 deactivateRate(userId:string,partnerId:string,rateId:string){return this.database.withUserContext(userId,async tx=>{await this.ensureManage(tx,partnerId);const r=await sql<{id:string}>`update buzzerhood.partner_rates set is_active=false,effective_to=coalesce(effective_to,current_date) where id=${rateId} and partner_id=${partnerId} returning id`.execute(tx);if(!r.rows[0])throw new ApiError(404,'PARTNER_RATE_NOT_FOUND','Rate tidak ditemukan.');this.logger.log({event:'partner.rate.deactivated',actorId:userId,partnerId,rateId});return this.rateTx(tx,partnerId,rateId);});}
 private async getTx(tx:Transaction<Database>,id:string){const r=await sql<PartnerRow>`select id,display_name,partner_kind,legal_name,partner_type,tier,category,niche,location,bio,verification_status,is_public from buzzerhood.partners where id=${id}`.execute(tx);const row=r.rows[0];if(!row)this.notFound();return this.dto(row);}
 private async ensureRead(tx:Transaction<Database>,id:string){const r=await sql<{allowed:boolean}>`select (buzzerhood.is_active_partner_member(${id}) or buzzerhood.has_permission('partners.read')) allowed from buzzerhood.partners where id=${id}`.execute(tx);if(r.rows[0]?.allowed!==true)this.notFound();}
 private async ensureManage(tx:Transaction<Database>,id:string){const r=await sql<{allowed:boolean}>`select buzzerhood.can_manage_partner(${id}) allowed from buzzerhood.partners where id=${id}`.execute(tx);if(r.rows[0]?.allowed!==true)this.notFound();}
 private async platformsTx(tx:Transaction<Database>,partnerId:string,id:string){const r=await sql<{id:string;platform:string;handle:string|null;profile_url:string|null;is_primary:boolean}>`select id,platform,handle,profile_url,is_primary from buzzerhood.partner_platform_accounts where partner_id=${partnerId} and id=${id}`.execute(tx);const x=r.rows[0];if(!x)throw new ApiError(404,'PARTNER_PLATFORM_NOT_FOUND','Akun platform tidak ditemukan.');return{id:x.id,platform:x.platform,handle:x.handle,profileUrl:x.profile_url,isPrimary:x.is_primary};}
 private async rateTx(tx:Transaction<Database>,partnerId:string,id:string){const r=await sql<{id:string;service_type:string;amount:string;currency:string;effective_from:string;effective_to:string|null;is_active:boolean;created_at:Date}>`select id,service_type,amount::text,currency,effective_from::text,effective_to::text,is_active,created_at from buzzerhood.partner_rates where partner_id=${partnerId} and id=${id}`.execute(tx);if(!r.rows[0])throw new ApiError(404,'PARTNER_RATE_NOT_FOUND','Rate tidak ditemukan.');return this.rateDto(r.rows[0]);}
 private dto(x:PartnerRow){return{id:x.id,displayName:x.display_name,kind:x.partner_kind,legalName:x.legal_name,partnerType:x.partner_type,tier:x.tier,category:x.category,niche:x.niche,location:x.location,bio:x.bio,verificationStatus:x.verification_status,isPublic:x.is_public};}
 private rateDto(x:{id:string;service_type:string;amount:string;currency:string;effective_from:string;effective_to:string|null;is_active:boolean;created_at:Date}){return{id:x.id,serviceType:x.service_type,amount:Number(x.amount),currency:x.currency.trim(),effectiveFrom:x.effective_from,effectiveTo:x.effective_to,isActive:x.is_active,createdAt:x.created_at};}
 private notFound():never{throw new ApiError(404,'PARTNER_NOT_FOUND','Partner tidak ditemukan.');}
}
