import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useAuth } from '@/features/auth/use-auth';
import { EmptyState } from '@/components/common/empty-state';
import { addPartnerAccount, addPartnerRate, deactivatePartnerRate, deletePartnerAccount, getMyPartner, getPartnerAccounts, getPartnerMetrics, getPartnerRates, safeMessage, updatePartnerProfile } from '@/features/onboarding/onboarding-api';
function usePartner(){const {user}=useAuth();return useQuery({queryKey:['my-partner',user?.id],queryFn:()=>getMyPartner(user?.id??''),enabled:Boolean(user)});}
function guard(data:Awaited<ReturnType<typeof getMyPartner>> | undefined){if(!data?.partners)return <EmptyState title="Partner belum tersedia" description="Daftar atau claim profile dari Workspace."/>;if(data.status!=='active')return <EmptyState title="Partner belum aktif" description="Aplikasi atau claim masih menunggu review internal."/>;return null;}
export function PartnerOverviewPage(){const q=usePartner();const blocked=guard(q.data);if(blocked)return blocked;const p=q.data!.partners!;return <section><p className="eyebrow">PARTNER WORKSPACE</p><h1>{p.display_name}</h1><div className="operational-grid"><article><span>Type</span><strong>{p.partner_type??p.partner_kind}</strong></article><article><span>Status</span><strong>{p.verification_status}</strong></article><article><span>Role</span><strong>{q.data!.role}</strong></article></div><EmptyState title="Campaign kosong" description="Campaign Engine belum diaktifkan."/></section>}
export function PartnerProfilePage(){const q=usePartner();const qc=useQueryClient();const [msg,setMsg]=useState('');const blocked=guard(q.data);if(blocked)return blocked;const p=q.data!.partners!;return <section><p className="eyebrow">PARTNER PROFILE</p><h1>{p.display_name}</h1><form className="auth-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await updatePartnerProfile(p.id,{display_name:String(f.get('display_name')),partner_type:String(f.get('partner_type')),category:String(f.get('category')),niche:String(f.get('niche')),location:String(f.get('location')),bio:String(f.get('bio'))});qc.invalidateQueries({queryKey:['my-partner']});setMsg('Profile tersimpan.')}catch(error){setMsg(safeMessage(error))}}}><label>Nama<input name="display_name" defaultValue={p.display_name}/></label><label>Type<input name="partner_type" defaultValue={p.partner_type??''}/></label><label>Category<input name="category" defaultValue={p.category??''}/></label><label>Niche<input name="niche" defaultValue={p.niche??''}/></label><label>Location<input name="location" defaultValue={p.location??''}/></label><label>Bio<textarea name="bio" defaultValue={p.bio??''}/></label><button className="btn-solid">Simpan</button><p>{msg}</p></form></section>}
export function PartnerPlatformsPage(){const q=usePartner();const qc=useQueryClient();const [msg,setMsg]=useState('');const blocked=guard(q.data);const accounts=useQuery({queryKey:['partner-accounts',q.data?.partner_id],queryFn:()=>getPartnerAccounts(q.data!.partner_id),enabled:!blocked&&Boolean(q.data)});if(blocked)return blocked;return <section><p className="eyebrow">PLATFORMS</p><h1>Platform accounts</h1><form className="inline-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await addPartnerAccount({partner_id:q.data!.partner_id,platform:String(f.get('platform')),handle:String(f.get('handle')),profile_url:String(f.get('profile_url')),is_primary:f.get('is_primary')==='on'});e.currentTarget.reset();qc.invalidateQueries({queryKey:['partner-accounts']});}catch(error){setMsg(safeMessage(error));}}}><input name="platform" placeholder="Platform" required/><input name="handle" placeholder="Handle"/><input name="profile_url" placeholder="URL"/><label><input name="is_primary" type="checkbox"/> Primary</label><button className="btn-solid">Tambah</button></form><p>{msg}</p><div className="ops-list">{accounts.data?.map(a=><article key={a.id}><strong>{a.platform} {a.handle}</strong><button onClick={async()=>{await deletePartnerAccount(a.id);qc.invalidateQueries({queryKey:['partner-accounts']});}}>Hapus</button></article>)}</div></section>}
export function PartnerMetricsPage(){const q=usePartner();const blocked=guard(q.data);const metrics=useQuery({queryKey:['partner-metrics',q.data?.partner_id],queryFn:()=>getPartnerMetrics(q.data!.partner_id),enabled:!blocked&&Boolean(q.data)});if(blocked)return blocked;return <section><p className="eyebrow">METRICS HISTORY</p><h1>Snapshot metrik</h1><div className="ops-list">{metrics.data?.map(m=><article key={m.id}><strong>{m.metric_type}: {m.metric_value.toLocaleString()}</strong><span>{m.metric_source} · {new Date(m.observed_at).toLocaleDateString()}</span></article>)}</div><p className="muted">Snapshot legacy menunjukkan tanggal import, bukan metrik live saat ini.</p></section>}
export function PartnerRatesPage(){const q=usePartner();const qc=useQueryClient();const blocked=guard(q.data);const rates=useQuery({queryKey:['partner-rates',q.data?.partner_id],queryFn:()=>getPartnerRates(q.data!.partner_id),enabled:!blocked&&Boolean(q.data)});if(blocked)return blocked;return <section><p className="eyebrow">RATE CARD</p><h1>Rate pribadi</h1><form className="inline-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await addPartnerRate({partner_id:q.data!.partner_id,service_type:String(f.get('service_type')),amount:Number(f.get('amount')),currency:String(f.get('currency')),effective_from:String(f.get('effective_from')),is_active:true});e.currentTarget.reset();qc.invalidateQueries({queryKey:['partner-rates']});}}><input name="service_type" placeholder="Service" required/><input name="amount" type="number" min="0" placeholder="Amount" required/><input name="currency" defaultValue="IDR" required/><input name="effective_from" type="date" required/><button className="btn-solid">Tambah</button></form><div className="ops-list">{rates.data?.map(r=><article key={r.id}><strong>{r.service_type} · {r.currency} {r.amount.toLocaleString()}</strong><span>{r.is_active?'Aktif':'Nonaktif'}</span>{r.is_active?<button onClick={async()=>{await deactivatePartnerRate(r.id);qc.invalidateQueries({queryKey:['partner-rates']});}}>Nonaktifkan</button>:null}</article>)}</div></section>}

