-- 0012: Campaign Engine core. All workflow mutations use guarded RPCs.
do $$ begin create type buzzerhood.campaign_status_v2 as enum ('draft','submitted','internal_review','changes_requested','planning','active','publishing','monitoring','reporting','completed','cancelled','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type buzzerhood.campaign_assignment_status as enum ('invited','accepted','declined','active','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type buzzerhood.campaign_deliverable_status as enum ('planned','in_progress','draft_submitted','revision_requested','internal_approved','client_approved','published','verified','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type buzzerhood.content_review_context as enum ('internal','client'); exception when duplicate_object then null; end $$;
do $$ begin create type buzzerhood.content_review_decision as enum ('approved','revision_requested','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type buzzerhood.publication_status as enum ('submitted','verified','rejected','removed'); exception when duplicate_object then null; end $$;

create table buzzerhood.services (id uuid primary key default gen_random_uuid(), name text not null unique, description text, is_active boolean not null default true, created_at timestamptz not null default now());
create table buzzerhood.campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references buzzerhood.organizations(id), name text not null, reference_code text unique, status buzzerhood.campaign_status_v2 not null default 'draft', objective_summary text, planned_start date, planned_end date, estimated_budget numeric(14,2), currency text not null default 'USD' check(length(currency)=3), created_by uuid not null references buzzerhood.profiles(id), submitted_at timestamptz, completed_at timestamptz, cancelled_at timestamptz, cancellation_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(planned_end is null or planned_start is null or planned_end >= planned_start), check(estimated_budget is null or estimated_budget >= 0));
create table buzzerhood.campaign_briefs (campaign_id uuid primary key references buzzerhood.campaigns(id) on delete cascade, objective text, description text, target_audience text, key_message text, call_to_action text, content_direction text, prohibited_content text, notes text, kpi_expectation text, context jsonb, updated_at timestamptz not null default now());
create table buzzerhood.campaign_services (campaign_id uuid references buzzerhood.campaigns(id) on delete cascade, service_id uuid references buzzerhood.services(id), primary key(campaign_id,service_id));
create table buzzerhood.campaign_target_platforms (campaign_id uuid references buzzerhood.campaigns(id) on delete cascade, platform text not null, primary key(campaign_id,platform));
create table buzzerhood.campaign_target_locations (campaign_id uuid references buzzerhood.campaigns(id) on delete cascade, location text not null, primary key(campaign_id,location));
create table buzzerhood.campaign_status_history (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references buzzerhood.campaigns(id) on delete cascade, from_status buzzerhood.campaign_status_v2, to_status buzzerhood.campaign_status_v2 not null, actor_id uuid not null references buzzerhood.profiles(id), reason text, created_at timestamptz not null default now());
create table buzzerhood.campaign_activity_logs (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references buzzerhood.campaigns(id) on delete cascade, event_type text not null, actor_id uuid not null references buzzerhood.profiles(id), metadata jsonb, created_at timestamptz not null default now());
create table buzzerhood.campaign_partner_assignments (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references buzzerhood.campaigns(id) on delete cascade, partner_id uuid not null references buzzerhood.partners(id), status buzzerhood.campaign_assignment_status not null default 'invited', invited_by uuid not null references buzzerhood.profiles(id), invited_at timestamptz not null default now(), responded_at timestamptz, accepted_at timestamptz, declined_reason text, agreed_fee numeric(14,2) check(agreed_fee is null or agreed_fee>=0), fee_currency text, rate_snapshot jsonb, internal_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(campaign_id,partner_id));
create table buzzerhood.campaign_deliverables (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references buzzerhood.campaign_partner_assignments(id) on delete cascade, title text not null, description text, platform text, due_date date, quantity integer not null default 1 check(quantity>0), status buzzerhood.campaign_deliverable_status not null default 'planned', platform_account_id uuid references buzzerhood.partner_platform_accounts(id), fee_component numeric(14,2) check(fee_component is null or fee_component>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table buzzerhood.content_submissions (id uuid primary key default gen_random_uuid(), deliverable_id uuid not null references buzzerhood.campaign_deliverables(id) on delete cascade, version integer not null check(version>0), status buzzerhood.submission_status not null default 'submitted', caption_body text, concept_notes text, asset_reference text, content_url text, submitted_by uuid not null references buzzerhood.profiles(id), submitted_at timestamptz not null default now(), unique(deliverable_id,version));
create table buzzerhood.content_submission_reviews (id uuid primary key default gen_random_uuid(), submission_id uuid not null references buzzerhood.content_submissions(id) on delete cascade, reviewer_id uuid not null references buzzerhood.profiles(id), reviewer_context buzzerhood.content_review_context not null, decision buzzerhood.content_review_decision not null, note text, created_at timestamptz not null default now());
create table buzzerhood.publications (id uuid primary key default gen_random_uuid(), deliverable_id uuid not null references buzzerhood.campaign_deliverables(id), content_submission_id uuid not null references buzzerhood.content_submissions(id), platform_account_id uuid references buzzerhood.partner_platform_accounts(id), publication_url text not null, status buzzerhood.publication_status not null default 'submitted', submitted_by uuid not null references buzzerhood.profiles(id), submitted_at timestamptz not null default now(), verified_by uuid references buzzerhood.profiles(id), verified_at timestamptz, verification_note text, unique(deliverable_id,content_submission_id));
create table buzzerhood.publication_metric_snapshots (id uuid primary key default gen_random_uuid(), publication_id uuid not null references buzzerhood.publications(id) on delete cascade, metric_type buzzerhood.metric_type not null, metric_value numeric(20,4) not null check(metric_value>=0), period_start date, period_end date, source text not null, captured_at timestamptz not null default now(), recorded_by uuid not null references buzzerhood.profiles(id), verification_note text, check(period_end is null or period_start is null or period_end>=period_start));

create index campaigns_org_status_idx on buzzerhood.campaigns(organization_id,status); create index assignments_partner_status_idx on buzzerhood.campaign_partner_assignments(partner_id,status); create index deliverables_assignment_status_idx on buzzerhood.campaign_deliverables(assignment_id,status); create index submissions_deliverable_version_idx on buzzerhood.content_submissions(deliverable_id,version desc); create index publications_deliverable_idx on buzzerhood.publications(deliverable_id);
create or replace function buzzerhood.campaign_visible(target_campaign_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from buzzerhood.campaigns c where c.id=target_campaign_id and (buzzerhood.is_active_organization_member(c.organization_id) or buzzerhood.has_permission('campaigns.read') or exists(select 1 from buzzerhood.campaign_partner_assignments a where a.campaign_id=c.id and buzzerhood.is_active_partner_member(a.partner_id)))); $$;
create or replace function buzzerhood.transition_campaign(input_campaign_id uuid,input_to buzzerhood.campaign_status_v2,input_reason text default null) returns buzzerhood.campaign_status_v2 language plpgsql security definer set search_path='' as $$ declare old buzzerhood.campaign_status_v2; org uuid; begin select status,organization_id into old,org from buzzerhood.campaigns where id=input_campaign_id for update; if old is null then raise exception 'campaign not found'; end if; if not (buzzerhood.has_permission('campaigns.manage') or (input_to in ('submitted','draft') and buzzerhood.is_active_organization_member(org))) then raise exception 'permission denied'; end if; if not ((old='draft' and input_to='submitted') or (old='submitted' and input_to='internal_review') or (old='internal_review' and input_to in ('changes_requested','planning')) or (old='changes_requested' and input_to='draft') or (old='planning' and input_to='active') or (old='active' and input_to='publishing') or (old='publishing' and input_to='monitoring') or (old='monitoring' and input_to='reporting') or (old='reporting' and input_to='completed') or input_to in ('cancelled','archived')) then raise exception 'invalid campaign transition'; end if; update buzzerhood.campaigns set status=input_to,submitted_at=case when input_to='submitted' then now() else submitted_at end,completed_at=case when input_to='completed' then now() else completed_at end,cancelled_at=case when input_to='cancelled' then now() else cancelled_at end,cancellation_reason=case when input_to='cancelled' then nullif(trim(input_reason),'') else cancellation_reason end,updated_at=now() where id=input_campaign_id; insert into buzzerhood.campaign_status_history(campaign_id,from_status,to_status,actor_id,reason) values(input_campaign_id,old,input_to,auth.uid(),nullif(trim(input_reason),'')); return input_to; end; $$;
create or replace function buzzerhood.respond_campaign_assignment(input_assignment_id uuid,input_response text,input_reason text default null) returns buzzerhood.campaign_assignment_status language plpgsql security definer set search_path='' as $$ declare current_status buzzerhood.campaign_assignment_status; target_partner uuid; next_status buzzerhood.campaign_assignment_status; begin select status,partner_id into current_status,target_partner from buzzerhood.campaign_partner_assignments where id=input_assignment_id for update; if current_status is null or not buzzerhood.is_active_partner_member(target_partner) then raise exception 'assignment not found'; end if; if current_status <> 'invited' or input_response not in ('accepted','declined') then raise exception 'invalid assignment response'; end if; next_status:=input_response::buzzerhood.campaign_assignment_status; update buzzerhood.campaign_partner_assignments set status=next_status,responded_at=now(),accepted_at=case when next_status='accepted' then now() end,declined_reason=case when next_status='declined' then nullif(trim(input_reason),'') end,updated_at=now() where id=input_assignment_id; return next_status; end; $$;
create or replace function buzzerhood.submit_content_version(input_deliverable_id uuid,input_caption_body text,input_concept_notes text default null,input_asset_reference text default null,input_content_url text default null) returns uuid language plpgsql security definer set search_path='' as $$ declare next_version integer; new_id uuid; begin if not exists(select 1 from buzzerhood.campaign_deliverables d join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where d.id=input_deliverable_id and buzzerhood.is_active_partner_member(a.partner_id)) then raise exception 'deliverable not found'; end if; perform pg_advisory_xact_lock(hashtextextended(input_deliverable_id::text,0)); select coalesce(max(version),0)+1 into next_version from buzzerhood.content_submissions where deliverable_id=input_deliverable_id; insert into buzzerhood.content_submissions(deliverable_id,version,caption_body,concept_notes,asset_reference,content_url,submitted_by) values(input_deliverable_id,next_version,input_caption_body,input_concept_notes,input_asset_reference,input_content_url,auth.uid()) returning id into new_id; update buzzerhood.campaign_deliverables set status='draft_submitted',updated_at=now() where id=input_deliverable_id; return new_id; end; $$;
revoke all on function buzzerhood.campaign_visible(uuid), buzzerhood.transition_campaign(uuid,buzzerhood.campaign_status_v2,text), buzzerhood.respond_campaign_assignment(uuid,text,text), buzzerhood.submit_content_version(uuid,text,text,text,text) from public; grant execute on function buzzerhood.campaign_visible(uuid), buzzerhood.transition_campaign(uuid,buzzerhood.campaign_status_v2,text), buzzerhood.respond_campaign_assignment(uuid,text,text), buzzerhood.submit_content_version(uuid,text,text,text,text) to authenticated;
do $$ declare t regclass; begin foreach t in array array['buzzerhood.services'::regclass,'buzzerhood.campaigns'::regclass,'buzzerhood.campaign_briefs'::regclass,'buzzerhood.campaign_services'::regclass,'buzzerhood.campaign_target_platforms'::regclass,'buzzerhood.campaign_target_locations'::regclass,'buzzerhood.campaign_status_history'::regclass,'buzzerhood.campaign_activity_logs'::regclass,'buzzerhood.campaign_partner_assignments'::regclass,'buzzerhood.campaign_deliverables'::regclass,'buzzerhood.content_submissions'::regclass,'buzzerhood.content_submission_reviews'::regclass,'buzzerhood.publications'::regclass,'buzzerhood.publication_metric_snapshots'::regclass] loop execute format('alter table %s enable row level security',t); execute format('alter table %s force row level security',t); end loop; end $$;
grant usage on schema buzzerhood to authenticated,service_role; grant select on buzzerhood.services,buzzerhood.campaigns,buzzerhood.campaign_briefs,buzzerhood.campaign_services,buzzerhood.campaign_target_platforms,buzzerhood.campaign_target_locations,buzzerhood.campaign_status_history,buzzerhood.campaign_activity_logs,buzzerhood.campaign_partner_assignments,buzzerhood.campaign_deliverables,buzzerhood.content_submissions,buzzerhood.content_submission_reviews,buzzerhood.publications,buzzerhood.publication_metric_snapshots to authenticated;
create policy campaigns_visible_read on buzzerhood.campaigns for select to authenticated using(buzzerhood.campaign_visible(id)); create policy campaign_briefs_visible_read on buzzerhood.campaign_briefs for select to authenticated using(buzzerhood.campaign_visible(campaign_id)); create policy assignments_visible_read on buzzerhood.campaign_partner_assignments for select to authenticated using(buzzerhood.campaign_visible(campaign_id)); create policy deliverables_visible_read on buzzerhood.campaign_deliverables for select to authenticated using(exists(select 1 from buzzerhood.campaign_partner_assignments a where a.id=assignment_id and buzzerhood.campaign_visible(a.campaign_id))); create policy submissions_visible_read on buzzerhood.content_submissions for select to authenticated using(exists(select 1 from buzzerhood.campaign_deliverables d join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where d.id=deliverable_id and buzzerhood.campaign_visible(a.campaign_id))); create policy publications_visible_read on buzzerhood.publications for select to authenticated using(exists(select 1 from buzzerhood.campaign_deliverables d join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where d.id=deliverable_id and buzzerhood.campaign_visible(a.campaign_id))); create policy metrics_visible_read on buzzerhood.publication_metric_snapshots for select to authenticated using(exists(select 1 from buzzerhood.publications p join buzzerhood.campaign_deliverables d on d.id=p.deliverable_id join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where p.id=publication_id and buzzerhood.campaign_visible(a.campaign_id))); create policy services_read on buzzerhood.services for select to authenticated using(is_active or buzzerhood.has_permission('campaigns.manage'));


create or replace function buzzerhood.create_campaign(input_organization_id uuid,input_name text,input_objective_summary text default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; begin
  if not buzzerhood.is_active_organization_member(input_organization_id) then raise exception 'permission denied'; end if;
  insert into buzzerhood.campaigns(organization_id,name,objective_summary,created_by) values(input_organization_id,nullif(trim(input_name),''),input_objective_summary,auth.uid()) returning id into new_id;
  insert into buzzerhood.campaign_briefs(campaign_id,objective) values(new_id,input_objective_summary);
  insert into buzzerhood.campaign_status_history(campaign_id,from_status,to_status,actor_id,reason) values(new_id,null,'draft',auth.uid(),'created');
  return new_id;
end; $$;

create or replace function buzzerhood.invite_campaign_partner(input_campaign_id uuid,input_partner_id uuid,input_agreed_fee numeric default null,input_fee_currency text default null,input_rate_snapshot jsonb default null,input_internal_notes text default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; begin
  if not buzzerhood.has_permission('campaigns.manage') then raise exception 'permission denied'; end if;
  insert into buzzerhood.campaign_partner_assignments(campaign_id,partner_id,invited_by,agreed_fee,fee_currency,rate_snapshot,internal_notes) values(input_campaign_id,input_partner_id,auth.uid(),input_agreed_fee,input_fee_currency,input_rate_snapshot,input_internal_notes) returning id into new_id;
  insert into buzzerhood.campaign_activity_logs(campaign_id,event_type,actor_id,metadata) values(input_campaign_id,'partner.invited',auth.uid(),jsonb_build_object('partner_id',input_partner_id,'assignment_id',new_id));
  return new_id;
end; $$;

create or replace function buzzerhood.create_campaign_deliverable(input_assignment_id uuid,input_title text,input_description text default null,input_platform text default null,input_due_date date default null,input_quantity integer default 1)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; begin
  if not buzzerhood.has_permission('campaigns.manage') then raise exception 'permission denied'; end if;
  insert into buzzerhood.campaign_deliverables(assignment_id,title,description,platform,due_date,quantity) values(input_assignment_id,nullif(trim(input_title),''),input_description,input_platform,input_due_date,coalesce(input_quantity,1)) returning id into new_id;
  return new_id;
end; $$;

create or replace function buzzerhood.review_content_submission(input_submission_id uuid,input_context buzzerhood.content_review_context,input_decision buzzerhood.content_review_decision,input_note text default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; deliverable uuid; campaign_org uuid; begin
  select s.deliverable_id,c.organization_id into deliverable,campaign_org from buzzerhood.content_submissions s join buzzerhood.campaign_deliverables d on d.id=s.deliverable_id join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id join buzzerhood.campaigns c on c.id=a.campaign_id where s.id=input_submission_id for update;
  if deliverable is null then raise exception 'submission not found'; end if;
  if input_context='internal' and not buzzerhood.has_permission('campaigns.manage') then raise exception 'permission denied'; end if;
  if input_context='client' and not buzzerhood.is_active_organization_member(campaign_org) then raise exception 'permission denied'; end if;
  insert into buzzerhood.content_submission_reviews(submission_id,reviewer_id,reviewer_context,decision,note) values(input_submission_id,auth.uid(),input_context,input_decision,nullif(trim(input_note),'')) returning id into new_id;
  update buzzerhood.content_submissions set status=case when input_decision='approved' then 'approved' when input_decision='revision_requested' then 'revision_requested' else 'rejected' end where id=input_submission_id;
  update buzzerhood.campaign_deliverables set status=case when input_decision='revision_requested' then 'revision_requested' when input_context='internal' and input_decision='approved' then 'internal_approved' when input_context='client' and input_decision='approved' then 'client_approved' else status end, updated_at=now() where id=deliverable;
  return new_id;
end; $$;

create or replace function buzzerhood.submit_publication(input_deliverable_id uuid,input_submission_id uuid,input_publication_url text,input_platform_account_id uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; begin
  if not exists(select 1 from buzzerhood.campaign_deliverables d join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where d.id=input_deliverable_id and d.status='client_approved' and buzzerhood.is_active_partner_member(a.partner_id)) then raise exception 'deliverable not publication-ready'; end if;
  insert into buzzerhood.publications(deliverable_id,content_submission_id,platform_account_id,publication_url,submitted_by) values(input_deliverable_id,input_submission_id,input_platform_account_id,input_publication_url,auth.uid()) returning id into new_id;
  update buzzerhood.campaign_deliverables set status='published',updated_at=now() where id=input_deliverable_id;
  return new_id;
end; $$;

create or replace function buzzerhood.verify_publication(input_publication_id uuid,input_decision buzzerhood.publication_status,input_note text default null)
returns buzzerhood.publication_status language plpgsql security definer set search_path='' as $$ declare deliverable uuid; begin
  if not buzzerhood.has_permission('campaigns.manage') then raise exception 'permission denied'; end if;
  if input_decision not in ('verified','rejected') then raise exception 'invalid publication decision'; end if;
  update buzzerhood.publications set status=input_decision,verified_by=auth.uid(),verified_at=now(),verification_note=nullif(trim(input_note),'') where id=input_publication_id returning deliverable_id into deliverable;
  if deliverable is null then raise exception 'publication not found'; end if;
  update buzzerhood.campaign_deliverables set status=case when input_decision='verified' then 'verified' else status end,updated_at=now() where id=deliverable;
  return input_decision;
end; $$;

create or replace function buzzerhood.record_publication_metric(input_publication_id uuid,input_metric_type buzzerhood.metric_type,input_metric_value numeric,input_source text,input_period_start date default null,input_period_end date default null,input_note text default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid; begin
  if not (buzzerhood.has_permission('campaigns.manage') or exists(select 1 from buzzerhood.publications p join buzzerhood.campaign_deliverables d on d.id=p.deliverable_id join buzzerhood.campaign_partner_assignments a on a.id=d.assignment_id where p.id=input_publication_id and buzzerhood.is_active_partner_member(a.partner_id))) then raise exception 'permission denied'; end if;
  insert into buzzerhood.publication_metric_snapshots(publication_id,metric_type,metric_value,period_start,period_end,source,recorded_by,verification_note) values(input_publication_id,input_metric_type,input_metric_value,input_period_start,input_period_end,input_source,auth.uid(),input_note) returning id into new_id;
  return new_id;
end; $$;

revoke all on function buzzerhood.create_campaign(uuid,text,text), buzzerhood.invite_campaign_partner(uuid,uuid,numeric,text,jsonb,text), buzzerhood.create_campaign_deliverable(uuid,text,text,text,date,integer), buzzerhood.review_content_submission(uuid,buzzerhood.content_review_context,buzzerhood.content_review_decision,text), buzzerhood.submit_publication(uuid,uuid,text,uuid), buzzerhood.verify_publication(uuid,buzzerhood.publication_status,text), buzzerhood.record_publication_metric(uuid,buzzerhood.metric_type,numeric,text,date,date,text) from public;
grant execute on function buzzerhood.create_campaign(uuid,text,text), buzzerhood.invite_campaign_partner(uuid,uuid,numeric,text,jsonb,text), buzzerhood.create_campaign_deliverable(uuid,text,text,text,date,integer), buzzerhood.review_content_submission(uuid,buzzerhood.content_review_context,buzzerhood.content_review_decision,text), buzzerhood.submit_publication(uuid,uuid,text,uuid), buzzerhood.verify_publication(uuid,buzzerhood.publication_status,text), buzzerhood.record_publication_metric(uuid,buzzerhood.metric_type,numeric,text,date,date,text) to authenticated;

insert into buzzerhood.schema_migrations(version,filename) values('0012','0012_campaign_engine_core.sql') on conflict(version) do nothing;


