import { apiRequest } from '@/lib/api/client';
export type Partner={id:string;display_name:string;partner_kind:string;partner_type:string|null;tier:string|null;category:string|null;niche:string|null;legal_name:string|null;location:string|null;bio:string|null;verification_status:string;is_public:boolean};
export type PartnerAccount={id:string;partner_id:string;platform:string;handle:string|null;profile_url:string|null;is_primary:boolean};
export type PartnerMetric={id:string;platform_account_id:string;metric_type:string;metric_value:number;observed_at:string;metric_source:string};
export type PartnerRate={id:string;partner_id:string;service_type:string;amount:number;currency:string;effective_from:string;effective_to:string|null;is_active:boolean};
type PartnerDto={id:string;displayName:string;partnerKind:string;partnerType:string|null;tier:string|null;category:string|null;niche:string|null;legalName:string|null;location:string|null;bio:string|null;verificationStatus:string;isPublic:boolean;membershipRole?:string};
export const safeMessage=(error:unknown)=>{const value=error instanceof Error?error.message.toLowerCase():'';if(value.includes('already pending'))return 'Permintaan claim sudah menunggu review.';if(value.includes('unavailable'))return 'Profil tidak tersedia untuk claim.';if(value.includes('permission'))return 'Anda tidak memiliki izin untuk tindakan ini.';if(value.includes('duplicate'))return 'Data tersebut sudah terdaftar.';return 'Operasi gagal. Periksa data lalu coba lagi.'};
export async function createClientOrganization(name:string,slug:string){return (await apiRequest<{id:string}>('/organizations',{method:'POST',body:{name,slug}})).id;}
export async function createPartnerApplication(input:{kind:string;displayName:string;partnerType:string;category:string;niche:string;location:string;bio:string}){return (await apiRequest<{id:string}>('/partner-applications',{method:'POST',body:input})).id;}
export async function requestPartnerClaim(partnerId:string,evidence:string){return (await apiRequest<{id:string}>('/partner-claims',{method:'POST',body:{partnerId,evidence}})).id;}
export async function reviewPartnerApplication(id:string,decision:'approved'|'rejected',note:string){await apiRequest('/admin/partner-applications/'+id+'/'+(decision==='approved'?'approve':'reject'),{method:'POST',body:{note:note||undefined}});}
export async function approvePartnerClaim(id:string,note=''){await apiRequest('/admin/partner-claims/'+id+'/approve',{method:'POST',body:{note:note||undefined}});}
export async function rejectPartnerClaim(id:string,note=''){await apiRequest('/admin/partner-claims/'+id+'/reject',{method:'POST',body:{note:note||undefined}});}
export async function searchClaimablePartners(search:string){const q=new URLSearchParams({search:search.trim(),page:'1',limit:'20'});const r=await apiRequest<{data:Array<{id:string;displayName:string;platform:string;handle:string|null;niche:string|null;tier:string|null;metricValue:number|null}>}>('/network?'+q);return r.data.map(v=>({id:v.id,display_name:v.displayName,platform:v.platform,handle:v.handle,niche:v.niche,tier:v.tier,metric_value:v.metricValue}));}
export async function getMyPartner(userId:string){void userId;const v=(await apiRequest<PartnerDto[]>('/me/partners'))[0];return v?{partner_id:v.id,status:'active',role:v.membershipRole??'',partners:{id:v.id,display_name:v.displayName,partner_kind:v.partnerKind,partner_type:v.partnerType,tier:v.tier,category:v.category,niche:v.niche,legal_name:v.legalName,location:v.location,bio:v.bio,verification_status:v.verificationStatus,is_public:v.isPublic}}:null;}
export async function getPartnerAccounts(partnerId:string){const r=await apiRequest<Array<{id:string;platform:string;handle:string|null;profileUrl:string|null;isPrimary:boolean}>>('/partners/'+partnerId+'/platforms');return r.map(v=>({id:v.id,partner_id:partnerId,platform:v.platform,handle:v.handle,profile_url:v.profileUrl,is_primary:v.isPrimary}));}
export async function getPartnerMetrics(partnerId:string){const r=await apiRequest<Array<{id:string;platformAccountId:string;metricType:string;metricValue:number;observedAt:string;metricSource:string}>>('/partners/'+partnerId+'/metrics');return r.map(v=>({id:v.id,platform_account_id:v.platformAccountId,metric_type:v.metricType,metric_value:v.metricValue,observed_at:v.observedAt,metric_source:v.metricSource}));}
export async function getPartnerRates(partnerId:string){const r=await apiRequest<Array<{id:string;serviceType:string;amount:number;currency:string;effectiveFrom:string;effectiveTo:string|null;isActive:boolean}>>('/partners/'+partnerId+'/rates');return r.map(v=>({id:v.id,partner_id:partnerId,service_type:v.serviceType,amount:v.amount,currency:v.currency,effective_from:v.effectiveFrom,effective_to:v.effectiveTo,is_active:v.isActive}));}
export async function updatePartnerProfile(id:string,input:Partial<Partner>){await apiRequest('/partners/'+id,{method:'PATCH',body:{displayName:input.display_name,legalName:input.legal_name,partnerType:input.partner_type,category:input.category,niche:input.niche,location:input.location,bio:input.bio}});}
export async function addPartnerAccount(i:{partner_id:string;platform:string;handle:string;profile_url:string;is_primary:boolean}){await apiRequest('/partners/'+i.partner_id+'/platforms',{method:'POST',body:{platform:i.platform,handle:i.handle||null,profileUrl:i.profile_url||null,isPrimary:i.is_primary}});}
export async function deletePartnerAccount(partnerId:string,id:string){await apiRequest('/partners/'+partnerId+'/platforms/'+id,{method:'DELETE'});}
export async function addPartnerRate(i:{partner_id:string;service_type:string;amount:number;currency:string;effective_from:string;is_active:boolean}){await apiRequest('/partners/'+i.partner_id+'/rates',{method:'POST',body:{serviceType:i.service_type,amount:i.amount,currency:i.currency,effectiveFrom:i.effective_from||undefined}});}
export async function deactivatePartnerRate(partnerId:string,id:string){await apiRequest('/partners/'+partnerId+'/rates/'+id,{method:'DELETE'});}
