import { getBuzzerhoodDb } from '@/lib/supabase/client';
export type Partner={id:string;display_name:string;partner_kind:string;partner_type:string|null;tier:string|null;category:string|null;niche:string|null;legal_name:string|null;location:string|null;bio:string|null;verification_status:string;is_public:boolean};
export type PartnerAccount={id:string;partner_id:string;platform:string;handle:string|null;profile_url:string|null;is_primary:boolean};
export type PartnerMetric={id:string;platform_account_id:string;metric_type:string;metric_value:number;observed_at:string;metric_source:string};
export type PartnerRate={id:string;partner_id:string;service_type:string;amount:number;currency:string;effective_from:string;effective_to:string|null;is_active:boolean};
type RpcResult={data:unknown;error:{message:string}|null}; type RpcDb={rpc:(name:string,args:Record<string,unknown>)=>PromiseLike<RpcResult>};
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await (getBuzzerhoodDb() as unknown as RpcDb).rpc(name,args);if(error)throw new Error(error.message);return data;}
export const safeMessage=(error:unknown)=>{const value=error instanceof Error?error.message.toLowerCase():'';if(value.includes('already pending'))return 'Permintaan claim sudah menunggu review.';if(value.includes('unavailable'))return 'Profil tidak tersedia untuk claim.';if(value.includes('permission'))return 'Anda tidak memiliki izin untuk tindakan ini.';if(value.includes('duplicate'))return 'Data tersebut sudah terdaftar.';return 'Operasi gagal. Periksa data lalu coba lagi.'};
export async function createClientOrganization(name:string,slug:string){return await rpc('create_client_organization',{input_name:name,input_slug:slug}) as string;}
export async function createPartnerApplication(input:{kind:string;displayName:string;partnerType:string;category:string;niche:string;location:string;bio:string}){return await rpc('create_partner_application',{input_kind:input.kind,input_display_name:input.displayName,input_partner_type:input.partnerType,input_category:input.category,input_niche:input.niche,input_location:input.location,input_bio:input.bio}) as string;}
export async function requestPartnerClaim(partnerId:string,evidence:string){return await rpc('request_partner_claim',{input_partner_id:partnerId,input_evidence:evidence}) as string;}
export async function reviewPartnerApplication(partnerId:string,decision:'approved'|'rejected',note:string){await rpc('review_partner_application',{input_partner_id:partnerId,input_decision:decision,input_review_note:note});}
export async function approvePartnerClaim(claimId:string,note=''){await rpc('approve_partner_claim',{input_claim_id:claimId,input_review_note:note});}
export async function rejectPartnerClaim(claimId:string,note=''){await rpc('reject_partner_claim',{input_claim_id:claimId,input_review_note:note});}
export async function searchClaimablePartners(search:string){let query=getBuzzerhoodDb().from('public_network_partners').select('*').limit(20);if(search.trim())query=query.or(`display_name.ilike.%${search.trim()}%,handle.ilike.%${search.trim()}%,platform.ilike.%${search.trim()}%,niche.ilike.%${search.trim()}%`);const {data,error}=await query;if(error)throw error;return data??[];}
export async function getMyPartner(userId:string){const {data,error}=await getBuzzerhoodDb().from('partner_members').select('partner_id,status,role,partners(*)').eq('profile_id',userId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data as unknown as {partner_id:string;status:string;role:string;partners:Partner|null}|null;}
export async function getPartnerAccounts(partnerId:string){const {data,error}=await getBuzzerhoodDb().from('partner_platform_accounts').select('*').eq('partner_id',partnerId).order('is_primary',{ascending:false});if(error)throw error;return data as PartnerAccount[];}
export async function getPartnerMetrics(partnerId:string){const accounts=await getPartnerAccounts(partnerId);if(!accounts.length)return[];const {data,error}=await getBuzzerhoodDb().from('partner_audience_metrics').select('*').in('platform_account_id',accounts.map(x=>x.id)).order('observed_at',{ascending:false});if(error)throw error;return data as PartnerMetric[];}
export async function getPartnerRates(partnerId:string){const {data,error}=await getBuzzerhoodDb().from('partner_rates').select('*').eq('partner_id',partnerId).order('created_at',{ascending:false});if(error)throw error;return data as PartnerRate[];}
export async function updatePartnerProfile(id:string,input:Partial<Partner>){const {error}=await getBuzzerhoodDb().from('partners').update(input).eq('id',id);if(error)throw error;}
export async function addPartnerAccount(input:{partner_id:string;platform:string;handle:string;profile_url:string;is_primary:boolean}){const {error}=await getBuzzerhoodDb().from('partner_platform_accounts').insert(input);if(error)throw error;}
export async function deletePartnerAccount(id:string){const {error}=await getBuzzerhoodDb().from('partner_platform_accounts').delete().eq('id',id);if(error)throw error;}
export async function addPartnerRate(input:{partner_id:string;service_type:string;amount:number;currency:string;effective_from:string;is_active:boolean}){const {error}=await getBuzzerhoodDb().from('partner_rates').insert(input);if(error)throw error;}
export async function deactivatePartnerRate(id:string){const {error}=await getBuzzerhoodDb().from('partner_rates').update({is_active:false,effective_to:new Date().toISOString().slice(0,10)}).eq('id',id);if(error)throw error;}
