import { randomBytes } from 'node:crypto';
import { Injectable } from '@nestjs/common';
import { sql } from 'kysely';
import { DatabaseService } from '../../common/database/database.service.js';
import { EmailService } from '../../common/email/email.service.js';
import { ApiError } from '../../common/errors/api-error.js';
import { postgresMessage } from '../../common/errors/postgres-error.js';
import { TokenService } from '../../common/security/token.service.js';
import type { CreateAdminUserInput, UpdateAdminUserRoleInput } from './admin-users.schemas.js';

@Injectable()
export class AdminUsersService {
  constructor(private readonly database: DatabaseService, private readonly email: EmailService, private readonly tokens: TokenService) {}

  list(userId: string) { return this.database.withUserContext(userId, async (transaction) => { const rows = await sql<{ id: string; email: string; display_name: string | null; status: string; roles: string[]; partner_memberships: string; created_at: Date }>`select u.id,u.email,p.display_name,u.status::text,array_remove(array_agg(distinct r.key),null) roles,count(distinct pm.id)::text partner_memberships,u.created_at from buzzerhood.users u left join buzzerhood.profiles p on p.id=u.id left join buzzerhood.user_roles ur on ur.profile_id=u.id and ur.revoked_at is null left join buzzerhood.roles r on r.id=ur.role_id left join buzzerhood.partner_members pm on pm.profile_id=u.id and pm.status in ('active','pending','suspended') group by u.id,p.display_name order by u.created_at desc`.execute(transaction); return rows.rows.map((row) => ({ id: row.id, email: row.email, displayName: row.display_name, status: row.status, roles: row.roles ?? [], partnerMembershipCount: Number(row.partner_memberships), createdAt: row.created_at })); }); }

  async create(userId: string, input: CreateAdminUserInput) { const token = randomBytes(32).toString('base64url'); try { const result = await this.database.withUserContext(userId, (transaction) => sql<{ id: string; email: string; display_name: string; status: string; role: string }>`select * from buzzerhood.admin_create_user_invitation(${input.email},${input.displayName},${input.role},${this.tokens.hashRefresh(token)},${new Date(Date.now()+86_400_000)})`.execute(transaction)); const created = result.rows[0]; if (!created) throw new Error(); await this.email.sendAccountInvitation({ email: created.email, displayName: created.display_name, token }); return { id: created.id, email: created.email, status: created.status, role: created.role }; } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && String(error.code) === '23505') throw new ApiError(409, 'USER_EMAIL_UNAVAILABLE', 'Email tidak dapat digunakan.'); throw new ApiError(400, 'USER_CREATE_FAILED', 'User tidak dapat dibuat.'); } }

  async role(actor: string, id: string, role: UpdateAdminUserRoleInput['role']) { try { await this.database.withUserContext(actor, (transaction) => sql`select buzzerhood.admin_set_user_role(${id},${role})`.execute(transaction)); return { id, role }; } catch (error) { const message = postgresMessage(error); if (/cannot change own role/i.test(message)) throw new ApiError(409, 'USER_ROLE_SELF_CHANGE_BLOCKED', 'Role akun sendiri tidak dapat diubah.'); if (/partner identity/i.test(message)) throw new ApiError(409, 'USER_ROLE_PARTNER_MEMBERSHIP', 'Akun Partner mendapat akses melalui membership Partner, bukan role internal.'); if (/super admin role/i.test(message)) throw new ApiError(403, 'USER_ROLE_SUPER_ADMIN_REQUIRED', 'Hanya Super Admin yang dapat mengelola role Super Admin.'); if (/user not found/i.test(message)) throw new ApiError(404, 'USER_NOT_FOUND', 'User tidak ditemukan.'); throw new ApiError(400, 'USER_ROLE_FAILED', 'Role user tidak dapat diubah.'); } }

  status(actor: string, id: string, status: 'active' | 'disabled') { return this.database.withUserContext(actor, async (transaction) => { try { await sql`select buzzerhood.admin_set_user_status(${id},${status})`.execute(transaction); return { id, status }; } catch { throw new ApiError(400, 'USER_STATUS_FAILED', 'Status user tidak dapat diubah.'); } }); }
  async resetPassword(actor: string, id: string) { const token = randomBytes(32).toString('base64url'); const result = await this.database.withUserContext(actor, (transaction) => sql<{ user_id: string; email: string; display_name: string | null }>`select * from buzzerhood.admin_create_password_reset(${id},${this.tokens.hashRefresh(token)},${new Date(Date.now()+1_800_000)})`.execute(transaction)); const target = result.rows[0]; if (!target) throw new ApiError(409, 'USER_RESET_UNAVAILABLE', 'Reset password hanya tersedia untuk akun aktif.'); await this.email.sendPasswordReset({ email: target.email, displayName: target.display_name, token }); return { id: target.user_id, delivered: true }; }
  async delete(actor: string, id: string) { try { await this.database.withUserContext(actor, (transaction) => sql`select buzzerhood.admin_delete_empty_user(${id})`.execute(transaction)); return { id, deleted: true }; } catch (error) { const message = postgresMessage(error); if (message.includes('business or audit references')) throw new ApiError(409, 'USER_DELETE_BLOCKED', 'Akun memiliki relasi bisnis atau audit. Nonaktifkan akun sebagai gantinya.'); if (message.includes('cannot delete own account')) throw new ApiError(409, 'USER_DELETE_SELF', 'Akun sendiri tidak dapat dihapus.'); if (message.includes('user not found')) throw new ApiError(404, 'USER_NOT_FOUND', 'User tidak ditemukan.'); throw new ApiError(400, 'USER_DELETE_FAILED', 'User tidak dapat dihapus.'); } }
}
