import { useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import './home-02-page.css';
import buzzerhoodWordmark from '@/assets/buzzerhood-wordmark.svg';

const services=[['◁','Media Placement','Portal berita, media online, media sosial, podcast, dan channel video.'],['◎','Creator & KOL Activation','Content creator, KOL, influencer, podcaster, dan storyteller.'],['♧','Community Activation','Komunitas kreatif, hobi, profesional, mahasiswa, dan komunitas daerah.'],['⌘','Buzzer Network','Akun media sosial, tim buzzer, campaign support, dan sebaran narasi terukur.'],['▣','Strategy & Consultation','Perencanaan strategi, insight, monitoring, reporting, dan optimasi campaign.']] as const;
const benefits=[['Jaringan Luas & Terverifikasi','Akses ke partner aktif dari berbagai kategori dan platform.'],['Strategi Berbasis Data','Perencanaan dan eksekusi yang terukur untuk setiap campaign.'],['Tim Berpengalaman','Didukung praktisi komunikasi, media, komunitas, dan digital.'],['Fleksibel & Custom','Disesuaikan dengan tujuan, audiens, timeline, dan skala campaign Anda.']] as const;
const cases=[['Brand Awareness','Produk Konsumen','https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=700'],['Event Amplification','Festival & Hiburan','https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=700'],['Launching Product','Teknologi','https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=700'],['Public Campaign','Isu & Edukasi','https://images.pexels.com/photos/3184431/pexels-photo-3184431.jpeg?auto=compress&cs=tinysrgb&w=700'],['Destination Campaign','Pariwisata & Daerah','https://images.pexels.com/photos/2474689/pexels-photo-2474689.jpeg?auto=compress&cs=tinysrgb&w=700']] as const;
const testimonials=[['Campaign berjalan lancar dan hasilnya sesuai ekspektasi. Tim Buzzerhood profesional dan responsif.','Marketing Manager','Brand FMCG'],['Jangkauan dan engagement meningkat signifikan. Buzzerhood memahami kebutuhan komunikasi kami.','Brand Director','Perusahaan Teknologi'],['Kolaborasi menyenangkan dan hasilnya nyata. Sangat direkomendasikan untuk brand yang ingin berkembang.','Founder','Brand Lifestyle']] as const;
const Arrow=({children}:{children:ReactNode})=><>{children}<span aria-hidden="true">→</span></>;
export function Home02Page(){const[open,setOpen]=useState(false);return <div className="h02"><header className="h02-nav"><Link className="h02-logo" to="/home-02">BUZZER<span>HOOD</span><small>IDEAS PEOPLE IMPACT</small></Link><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Menu</button><nav className={open?'open':''}><a href="#beranda-02">Beranda</a><a href="#layanan-02">Layanan</a><a href="#jaringan-02">Jaringan</a><a href="#studi-kasus-02">Studi Kasus</a><a href="#tentang-02">Tentang</a></nav><Link className="h02-pill" to="/campaign-request"><Arrow>Hubungi Kami</Arrow></Link></header><main>
<section className="h02-hero" id="beranda-02"><div className="h02-container"><div className="h02-hero-copy"><p className="h02-kicker"><b>IDEAS</b> PEOPLE IMPACT</p><h1>Media,<br/>Influence &amp;<br/><em>Distribution<br/>Network</em></h1><p>Bersama jaringan media, creator, komunitas, dan buzzer, kami membantu brand Anda menjadi lebih dikenal, lebih relevan, dan berdampak nyata.</p><div className="h02-actions"><Link className="h02-pill" to="/campaign-request"><Arrow>Diskusikan Campaign</Arrow></Link><a className="h02-outline" href="#layanan-02">Lihat Layanan</a></div><div className="h02-mini-stats">{[['124+','Network Partner'],['206+','Platform Accounts'],['100M+','Estimated Reach'],['Real','& Measurable']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></div></div></section>
<section className="h02-about" id="tentang-02"><div className="h02-container h02-about-grid"><div><p className="h02-label">Tentang Kami</p><h2>Buzzerhood dibangun untuk <em>amplifikasi brand di dunia digital.</em></h2></div><div><p>Kami menghubungkan brand dengan jaringan media, content creator, komunitas, dan buzzer di berbagai platform. Dengan strategi, data, dan eksekusi terukur, kami membantu brand menjangkau audiens yang tepat.</p><a href="#jaringan-02">Pelajari lebih lanjut →</a></div><figure><img src="https://images.pexels.com/photos/3184436/pexels-photo-3184436.jpeg?auto=compress&cs=tinysrgb&w=700" alt="Tim berdiskusi tentang strategi campaign"/><figcaption>▶ &nbsp; Lihat Video Tentang Kami</figcaption></figure></div></section>
<section className="h02-dark" id="layanan-02"><div className="h02-container"><div className="h02-heading"><div><p className="h02-label">Layanan Kami</p><h2>Solusi Lengkap<br/>Untuk Kebutuhan Campaign Anda.</h2></div><p>Dari strategi hingga eksekusi, kami siap mendukung berbagai kebutuhan komunikasi brand Anda.<a href="#kontak-02">Lihat Semua Layanan →</a></p></div><div className="h02-services">{services.map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section className="h02-why" id="jaringan-02"><img src="https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=1100" alt="Strategist merencanakan campaign"/><div><p className="h02-label">Kenapa Buzzerhood</p><h2>Lebih Dari Sekadar Buzzer.</h2>{benefits.map((x,i)=><article key={x[0]}><i>{['♧','⌁','☆','☷'][i]}</i><p><strong>{x[0]}</strong><span>{x[1]}</span></p></article>)}</div></section>
<section className="h02-numbers"><div className="h02-container"><div><p className="h02-label">Angka Bicara</p><h2>Jangkauan Lebih Luas,<br/>Dampak Lebih Nyata.</h2></div>{[['124+','Network Partner'],['206+','Platform Accounts'],['100M+','Potential Reach'],['5.000+','Campaign Executed']].map(x=><div className="h02-number" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
<section className="h02-dark" id="studi-kasus-02"><div className="h02-container"><div className="h02-heading"><div><p className="h02-label">Studi Kasus</p><h2>Berbagai Brand<br/>Telah Bertumbuh Bersama Kami.</h2></div><a href="#kontak-02">Lihat Semua Studi Kasus →</a></div><div className="h02-cases">{cases.map(x=><article key={x[0]}><img src={x[2]} alt={x[0]} loading="lazy"/><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className="h02-brands"><div className="h02-container"><b>Bekerja Bersama<br/>Berbagai Brand</b><div><strong>Telkomsel</strong><strong>gojek</strong><strong>BCA</strong><strong>traveloka</strong><strong>SAMSUNG</strong><strong>nutrifood</strong><span>&amp; Banyak Lagi</span></div></div></section>
<section className="h02-dark h02-testimonials"><div className="h02-container"><div><p className="h02-label">Apa Kata</p><h2>Apa Kata<br/>Klien Kami</h2><p>Kepercayaan mereka memotivasi kami untuk terus memberikan yang terbaik.</p></div>{testimonials.map(x=><blockquote key={x[1]}><b>“</b><p>{x[0]}</p><footer><i>{x[1][0]}</i><strong>{x[1]}<small>{x[2]}</small></strong></footer></blockquote>)}</div></section>
<section className="h02-final" id="kontak-02"><div className="h02-container"><h2>Siap Menggerakkan<br/>Jaringan Untuk Campaign<br/>Berikutnya?</h2><p>Diskusikan kebutuhan campaign Anda. Dari ide, strategi, hingga eksekusi, kami siap membantu.</p><Link className="h02-pill" to="/campaign-request"><Arrow>Diskusikan Campaign</Arrow></Link></div></section></main>
<footer className="h02-footer"><div className="h02-container"><Link className="h02-footer-logo" to="/home-02" aria-label="Buzzerhood home"><img src={buzzerhoodWordmark} alt="Buzzerhood — Ideas People Impact" /></Link><div><b>Menu</b><a href="#beranda-02">Beranda</a><a href="#layanan-02">Layanan</a><a href="#jaringan-02">Jaringan</a><a href="#studi-kasus-02">Studi Kasus</a></div><div><b>Lainnya</b><a href="#kontak-02">Karir</a><a href="#kontak-02">Blog</a><a href="#kontak-02">FAQ</a><a href="#kontak-02">Privasi</a></div><div><b>Hubungi Kami</b><a href="mailto:hello@dev-buzzerhood.carubra.com">hello@dev-buzzerhood.carubra.com</a><div className="h02-socials" aria-label="Social media"><a href="#kontak-02" aria-label="Instagram">IG</a><a href="#kontak-02" aria-label="LinkedIn">in</a><a href="#kontak-02" aria-label="YouTube">▶</a><a href="#kontak-02" aria-label="TikTok">♪</a><a href="#kontak-02" aria-label="X">X</a></div></div></div><div className="h02-container h02-copy"><span>© 2026 Buzzerhood. All rights reserved.</span><span>A Stronger Creative Ecosystem</span></div></footer></div>}
