import { Link } from 'react-router-dom';
import { packages, products, teamRoles } from '@/data/legacy/public-content';
import { PublicNetworkPreview } from '@/features/network/public-network-preview';

const tickerItems = [
  { label: 'Network Growth', number: '+18% QoQ' },
  { label: 'Campaign Revenue', number: 'Rp750 Jt/bln' },
  { label: 'Reach', number: '3,365,742+' },
  { label: 'Engagement', number: '4.8%' },
  { label: 'Active Media', number: '23+' },
  { label: 'Active Influencer', number: '101+' },
  { label: 'Repeat Client', number: '34+' },
];

export function PublicHomePage() {
  return <div className="site"><PublicNavbar />
    <section className="hero" id="beranda"><div className="hero-bg" /><div className="wrap hero-grid"><div><p className="eyebrow">BUZZERHOOD NETWORK</p><h1>Media, Influence &amp; Distribution Network</h1><p className="lead">Buzzerhood menghubungkan brand dengan media, KOL, influencer, creator, dan komunitas untuk campaign yang lebih terarah, terukur, dan siap dijalankan.</p><div className="hero-cta"><Link className="btn-solid" to="/campaign-request">Diskusikan Campaign</Link><a className="btn-ghost" href="#database">Lihat Network Database</a></div></div><SignalGraphic /></div><MetricsTicker /></section>
    <section className="position"><div className="wrap position-grid reveal"><blockquote>Buzzerhood dibangun sebagai <span className="hi">distribution infrastructure.</span><br /><span className="strike">Bukan sekadar jasa buzzer.</span></blockquote><div className="support"><div className="position-photo"><div className="photo-tile"><img src="https://images.pexels.com/photos/36733315/pexels-photo-36733315.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Tim Buzzerhood menyusun strategi campaign" loading="lazy" /><span className="cap">Strategy session — tim campaign</span></div></div><p>Kebanyakan jasa buzzer berhenti di penyebaran pesan. Buzzerhood menata seluruh alur: data jaringan, strategi distribusi, pemilihan partner, monitoring publikasi, sampai reporting.</p></div></div></section>
    <section className="wrap"><div className="section-head"><p className="eyebrow">OPERATIONAL TEAM</p><h2>Delapan peran, satu campaign</h2></div><div className="team-grid">{teamRoles.map((role, index) => <div className="team-cell" key={role}><span className="mark">{String(index + 1).padStart(2, '0')}</span><span className="role">{role}</span></div>)}</div></section>
    <section className="wrap" id="jaringan"><div className="head-with-photo"><div className="section-head"><p className="eyebrow">NETWORK COMPOSITION</p><h2>Satu database, tiga lapisan jaringan</h2></div><div className="photo-row"><img src="https://images.pexels.com/photos/7652054/pexels-photo-7652054.jpeg?auto=compress&cs=tinysrgb&w=700" alt="Creator bekerja dengan kamera" loading="lazy" /><img src="https://images.pexels.com/photos/7651804/pexels-photo-7651804.jpeg?auto=compress&cs=tinysrgb&w=700" alt="Media sosial dan publikasi" loading="lazy" /></div></div><div className="comp-cols"><div className="comp-col"><p className="tnum">01</p><h3>Media & Publisher</h3><p>Akun media, website, dan public figure untuk memperluas exposure campaign.</p></div><div className="comp-col"><p className="tnum">02</p><h3>KOL & Influencer</h3><p>Creator dengan audiens spesifik dari nano sampai mega tier.</p></div><div className="comp-col"><p className="tnum">03</p><h3>Community Network</h3><p>Komunitas lokal dan niche untuk conversation serta credibility layer.</p></div></div></section>
    <section className="wrap" id="layanan"><div className="section-head"><p className="eyebrow">SERVICES</p><h2>Tujuh cara menyalurkan pesan brand</h2></div><div className="product-list">{products.map((product) => <article className="product-row" key={product.name}><div><h3>{product.name}</h3><p className="pfreq">{product.frequency}</p><p className="pdesc">{product.description}</p></div><ul>{product.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>
    <section className="wrap" id="paket"><div className="section-head"><p className="eyebrow">PACKAGES</p><h2>Skala campaign, dari lokal sampai nasional</h2></div><div className="pkg-list">{packages.map((item, index) => <article className="pkg-row" key={item.name}><span className="pkg-idx">{String(index + 1).padStart(2, '0')}</span><div><h3 className="pkg-name">{item.name}</h3><p className="pkg-sub">{item.subtitle}</p></div><strong className="pkg-price">{item.price}</strong></article>)}</div></section>
    <section className="wrap"><div className="target-grid"><div><p className="eyebrow">NETWORK TARGET</p><h2>Menuju 5.000 akun digital dalam satu database</h2><p className="lead">MVP menyiapkan fondasi agar jaringan legacy dapat dimigrasikan bertahap ke database `buzzerhood`, diverifikasi, dan dipakai untuk campaign internal.</p></div><div className="target-fields"><div><span className="target-num">5.000</span><span className="target-lbl">target akun</span></div><div><span className="target-num">124</span><span className="target-lbl">record legacy</span></div><div><span className="target-num">7</span><span className="target-lbl">platform kategori</span></div></div></div></section>
    <PublicNetworkPreview />`r`n    <section className="wrap cta-final" id="kontak"><p className="eyebrow">READY TO DISTRIBUTE?</p><h2>Siap menggerakkan jaringan untuk campaign berikutnya?</h2><p>Buzzerhood menyiapkan infrastruktur distribusi dari strategi sampai laporan.</p><Link className="btn-solid" to="/campaign-request">Mulai Campaign</Link></section><PublicFooter /></div>;
}

function PublicNavbar() { return <header className="nav"><Link className="brand" to="/">BUZZER<span>HOOD</span></Link><nav aria-label="Navigasi utama"><a href="#jaringan">Jaringan</a><a href="#layanan">Layanan</a><a href="#paket">Paket</a><a href="#database">Database</a><a href="#kontak">Kontak</a></nav><Link className="nav-cta" to="/campaign-request">Mulai Campaign</Link></header>; }
function SignalGraphic() { return <div className="signal-wrap" aria-label="Ilustrasi jaringan distribusi"><div className="pulse" /><div className="pulse pulse2" /><div className="pulse pulse3" /><span className="node node-a">Brand</span><span className="node node-b">Media</span><span className="node node-c">KOL</span><span className="node node-d">Community</span><strong>Distribution OS</strong></div>; }
function MetricsTicker() { return <div className="ticker-band" aria-label="Metrik jaringan"><div className="ticker-track">{[...tickerItems, ...tickerItems].map((item, index) => <span className="tick" key={`${item.label}-${index}`}><strong>{item.number}</strong>{item.label}</span>)}</div></div>; }
function PublicFooter() { return <footer className="foot-grid"><div><Link className="foot-brand" to="/">BUZZER<span>HOOD</span></Link><p>Media, Influence & Distribution Network.</p></div><div className="foot-cols"><div><h3>Contact</h3><a href="mailto:hello@buzzerhood.com">hello@buzzerhood.com</a><a href="https://buzzerhood.com">buzzerhood.com</a></div><div><h3>Product</h3><a href="#layanan">Media Blast</a><a href="#layanan">KOL Campaign</a><a href="#layanan">Digital PR</a><a href="#layanan">Brand Reputation</a></div><div><h3>Navigate</h3><a href="#jaringan">Jaringan</a><a href="#paket">Paket</a><a href="#database">Database</a><a href="#kontak">Kontak</a></div></div><p className="foot-bottom">© 2026 Buzzerhood. Legacy design preserved for React migration.</p></footer>; }



