import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { createCampaign,getAdminCampaigns,getClientCampaigns,getPartnerAssignments,getPartnerAssignmentDeliverables,respondToAssignment,submitContentVersion,transitionCampaign } from '@/features/campaigns/campaign-api';
import { useWorkspaceAccess } from '@/features/workspaces/use-workspace-access';
import type { CampaignStatus } from '@/features/campaigns/campaign-types';
import './admin-campaigns-page.css';

export function ClientCampaignsPage(){const access=useWorkspaceAccess();const organization=access.data?.find(v=>v.kind==='client'&&v.organizationId);const qc=useQueryClient();const campaigns=useQuery({queryKey:['campaigns','client',organization?.organizationId],queryFn:getClientCampaigns,enabled:Boolean(organization)});const [message,setMessage]=useState('');async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!organization?.organizationId)return;const form=new FormData(event.currentTarget);try{await createCampaign(organization.organizationId,String(form.get('name')),String(form.get('objective'))||undefined);event.currentTarget.reset();await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Campaign berhasil dibuat.')}catch(error){setMessage(error instanceof Error?error.message:'Campaign gagal dibuat.')}}async function submit(id:string){try{await transitionCampaign(id,'submitted');await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Campaign dikirim untuk review internal.')}catch(error){setMessage(error instanceof Error?error.message:'Campaign gagal dikirim.')}}return <section><p className="eyebrow">CLIENT CAMPAIGNS</p><h1>Campaign brief</h1><p className="muted">Buat draft lalu kirim ke tim internal.</p>{organization?<form className="auth-card" onSubmit={create}><label>Nama campaign<input name="name" required minLength={2}/></label><label>Ringkasan tujuan<textarea name="objective" rows={4}/></label><button className="btn-solid">Buat campaign</button></form>:<p>Organisasi client tidak ditemukan.</p>}<p>{message}</p><div className="ops-list">{campaigns.data?.map(c=><article key={c.id}><strong>{c.name}</strong><span>{c.status} · {c.currency} {c.estimated_budget?.toLocaleString()??0}</span>{['draft','changes_requested'].includes(c.status)?<button onClick={()=>submit(c.id)}>Kirim review</button>:null}</article>)}</div></section>}

export function PartnerCampaignsPage(){const qc=useQueryClient();const assignments=useQuery({queryKey:['campaigns','partner','assignments'],queryFn:getPartnerAssignments});const [selected,setSelected]=useState<string|null>(null);const deliverables=useQuery({queryKey:['campaigns','partner','deliverables',selected],queryFn:()=>getPartnerAssignmentDeliverables(selected??''),enabled:Boolean(selected)});const [message,setMessage]=useState('');async function respond(id:string,response:'accepted'|'declined'){try{await respondToAssignment(id,response,response==='declined'?'Ditolak melalui Partner workspace':undefined);await qc.invalidateQueries({queryKey:['campaigns','partner']});setMessage('Respons assignment tersimpan.')}catch(error){setMessage(error instanceof Error?error.message:'Respons gagal disimpan.')}}async function submit(event:React.FormEvent<HTMLFormElement>,deliverableId:string){event.preventDefault();const form=new FormData(event.currentTarget);try{await submitContentVersion(deliverableId,{captionBody:String(form.get('caption')),conceptNotes:String(form.get('notes'))||undefined,contentUrl:String(form.get('url'))||undefined});event.currentTarget.reset();setMessage('Versi konten terkirim.')}catch(error){setMessage(error instanceof Error?error.message:'Konten gagal dikirim.')}}return <section><p className="eyebrow">PARTNER CAMPAIGNS</p><h1>Assignment dan deliverable</h1><p>{message}</p><div className="ops-list">{assignments.data?.map(a=><article key={a.id}><strong>Campaign {a.campaign_id.slice(0,8)}</strong><span>{a.status} · {a.fee_currency??'IDR'} {a.agreed_fee?.toLocaleString()??0}</span>{a.status==='invited'?<><button onClick={()=>respond(a.id,'accepted')}>Terima</button><button onClick={()=>respond(a.id,'declined')}>Tolak</button></>:null}<button onClick={()=>setSelected(a.id)}>Lihat deliverable</button></article>)}</div>{selected?<div className="ops-list">{deliverables.data?.map(d=><article key={d.id}><strong>{d.title}</strong><span>{d.platform??'Platform'} · {d.status} · qty {d.quantity}</span><form className="auth-card" onSubmit={event=>submit(event,d.id)}><label>Caption<textarea name="caption" required rows={4}/></label><label>Catatan konsep<textarea name="notes" rows={3}/></label><label>URL konten<input name="url" type="url"/></label><button className="btn-solid">Kirim versi konten</button></form></article>)}</div>:null}</section>}

const adminTransitions:CampaignStatus[]=['internal_review','changes_requested','planning','active','publishing','monitoring','reporting','completed','archived'];
const statusLabels:Record<CampaignStatus,string>={draft:'Draft',submitted:'Menunggu review',internal_review:'Review internal',changes_requested:'Perlu revisi',planning:'Perencanaan',active:'Aktif',publishing:'Publikasi',monitoring:'Monitoring',reporting:'Pelaporan',completed:'Selesai',cancelled:'Dibatalkan',archived:'Diarsipkan'};

export function AdminCampaignsPage(){
  const qc=useQueryClient();
  const campaigns=useQuery({queryKey:['campaigns','admin'],queryFn:getAdminCampaigns});
  const [message,setMessage]=useState('');
  const [filter,setFilter]=useState<'all'|'attention'|'active'|'completed'>('all');
  const [busyId,setBusyId]=useState<string|null>(null);
  const data=campaigns.data??[];
  const attentionStatuses:CampaignStatus[]=['submitted','internal_review','changes_requested'];
  const activeStatuses:CampaignStatus[]=['planning','active','publishing','monitoring','reporting'];
  const filtered=data.filter(c=>filter==='all'||(filter==='attention'&&attentionStatuses.includes(c.status))||(filter==='active'&&activeStatuses.includes(c.status))||(filter==='completed'&&['completed','archived'].includes(c.status)));
  async function move(id:string,to:CampaignStatus){setBusyId(id);setMessage('');try{await transitionCampaign(id,to,'Updated through Admin workspace');await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Status campaign berhasil diperbarui.')}catch(error){setMessage(error instanceof Error?error.message:'Status gagal diperbarui.')}finally{setBusyId(null)}}
  return <section className="admin-campaigns-page">
    <header className="campaign-page-heading"><div><p className="eyebrow">ADMIN CAMPAIGNS</p><h1>Operasi campaign</h1><p>Kelola antrean review dan pantau campaign tanpa membuka detail teknis.</p></div><div className="campaign-security-note"><span aria-hidden="true"/><strong>Akses terverifikasi</strong><small>Semua perubahan divalidasi Backend.</small></div></header>
    <div className="campaign-summary" aria-label="Ringkasan campaign"><article><span>Total campaign</span><strong>{data.length}</strong></article><article><span>Butuh perhatian</span><strong>{data.filter(c=>attentionStatuses.includes(c.status)).length}</strong></article><article><span>Sedang berjalan</span><strong>{data.filter(c=>activeStatuses.includes(c.status)).length}</strong></article><article><span>Selesai</span><strong>{data.filter(c=>c.status==='completed').length}</strong></article></div>
    <div className="campaign-toolbar"><div role="group" aria-label="Filter campaign">{([['all','Semua'],['attention','Butuh perhatian'],['active','Berjalan'],['completed','Selesai']] as const).map(([value,label])=><button key={value} type="button" className={filter===value?'active':''} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div><span>{filtered.length} campaign ditampilkan</span></div>
    {message?<p className="campaign-message" role="status">{message}</p>:null}
    {campaigns.isLoading?<div className="campaign-state">Memuat campaign…</div>:null}
    {campaigns.isError?<div className="campaign-state error">Campaign gagal dimuat. Coba muat ulang halaman.</div>:null}
    {!campaigns.isLoading&&!campaigns.isError&&filtered.length===0?<div className="campaign-state"><strong>Belum ada campaign</strong><span>Tidak ada data pada filter ini.</span></div>:null}
    <div className="campaign-grid">{filtered.map(c=><article className="campaign-card" key={c.id}><div className="campaign-card-top"><div><span className={`campaign-status status-${c.status}`}>{statusLabels[c.status]}</span><h2>{c.name}</h2><p>{c.organization_name??'Organisasi belum bernama'}</p></div><span className="campaign-reference">{c.reference_code??`#${c.id.slice(0,8).toUpperCase()}`}</span></div><p className="campaign-objective">{c.objective_summary||'Ringkasan tujuan campaign belum diisi.'}</p><dl><div><dt>Budget</dt><dd>{c.estimated_budget===null?'Belum ditentukan':`${c.currency} ${c.estimated_budget.toLocaleString('id-ID')}`}</dd></div><div><dt>Dibuat</dt><dd>{new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'}).format(new Date(c.created_at))}</dd></div></dl><div className="campaign-card-action"><label htmlFor={`status-${c.id}`}>Tahap berikutnya</label><select id={`status-${c.id}`} defaultValue="" disabled={busyId===c.id} onChange={event=>{if(event.target.value){void move(c.id,event.target.value as CampaignStatus);event.currentTarget.value=''}}}><option value="">Pilih perubahan status</option>{adminTransitions.filter(status=>status!==c.status).map(status=><option key={status} value={status}>{statusLabels[status]}</option>)}</select></div></article>)}</div>
  </section>
}
