import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { createCampaign,getAdminCampaigns,getClientCampaigns,getPartnerAssignments,getPartnerAssignmentDeliverables,respondToAssignment,submitContentVersion,transitionCampaign } from '@/features/campaigns/campaign-api';
import { useWorkspaceAccess } from '@/features/workspaces/use-workspace-access';
import type { CampaignStatus } from '@/features/campaigns/campaign-types';

export function ClientCampaignsPage(){const access=useWorkspaceAccess();const organization=access.data?.find(v=>v.kind==='client'&&v.organizationId);const qc=useQueryClient();const campaigns=useQuery({queryKey:['campaigns','client',organization?.organizationId],queryFn:getClientCampaigns,enabled:Boolean(organization)});const [message,setMessage]=useState('');async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!organization?.organizationId)return;const form=new FormData(event.currentTarget);try{await createCampaign(organization.organizationId,String(form.get('name')),String(form.get('objective'))||undefined);event.currentTarget.reset();await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Campaign berhasil dibuat.')}catch(error){setMessage(error instanceof Error?error.message:'Campaign gagal dibuat.')}}async function submit(id:string){try{await transitionCampaign(id,'submitted');await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Campaign dikirim untuk review internal.')}catch(error){setMessage(error instanceof Error?error.message:'Campaign gagal dikirim.')}}return <section><p className="eyebrow">CLIENT CAMPAIGNS</p><h1>Campaign brief</h1><p className="muted">Buat draft lalu kirim ke tim internal.</p>{organization?<form className="auth-card" onSubmit={create}><label>Nama campaign<input name="name" required minLength={2}/></label><label>Ringkasan tujuan<textarea name="objective" rows={4}/></label><button className="btn-solid">Buat campaign</button></form>:<p>Organisasi client tidak ditemukan.</p>}<p>{message}</p><div className="ops-list">{campaigns.data?.map(c=><article key={c.id}><strong>{c.name}</strong><span>{c.status} · {c.currency} {c.estimated_budget?.toLocaleString()??0}</span>{['draft','changes_requested'].includes(c.status)?<button onClick={()=>submit(c.id)}>Kirim review</button>:null}</article>)}</div></section>}

export function PartnerCampaignsPage(){const qc=useQueryClient();const assignments=useQuery({queryKey:['campaigns','partner','assignments'],queryFn:getPartnerAssignments});const [selected,setSelected]=useState<string|null>(null);const deliverables=useQuery({queryKey:['campaigns','partner','deliverables',selected],queryFn:()=>getPartnerAssignmentDeliverables(selected??''),enabled:Boolean(selected)});const [message,setMessage]=useState('');async function respond(id:string,response:'accepted'|'declined'){try{await respondToAssignment(id,response,response==='declined'?'Ditolak melalui Partner workspace':undefined);await qc.invalidateQueries({queryKey:['campaigns','partner']});setMessage('Respons assignment tersimpan.')}catch(error){setMessage(error instanceof Error?error.message:'Respons gagal disimpan.')}}async function submit(event:React.FormEvent<HTMLFormElement>,deliverableId:string){event.preventDefault();const form=new FormData(event.currentTarget);try{await submitContentVersion(deliverableId,{captionBody:String(form.get('caption')),conceptNotes:String(form.get('notes'))||undefined,contentUrl:String(form.get('url'))||undefined});event.currentTarget.reset();setMessage('Versi konten terkirim.')}catch(error){setMessage(error instanceof Error?error.message:'Konten gagal dikirim.')}}return <section><p className="eyebrow">PARTNER CAMPAIGNS</p><h1>Assignment dan deliverable</h1><p>{message}</p><div className="ops-list">{assignments.data?.map(a=><article key={a.id}><strong>Campaign {a.campaign_id.slice(0,8)}</strong><span>{a.status} · {a.fee_currency??'IDR'} {a.agreed_fee?.toLocaleString()??0}</span>{a.status==='invited'?<><button onClick={()=>respond(a.id,'accepted')}>Terima</button><button onClick={()=>respond(a.id,'declined')}>Tolak</button></>:null}<button onClick={()=>setSelected(a.id)}>Lihat deliverable</button></article>)}</div>{selected?<div className="ops-list">{deliverables.data?.map(d=><article key={d.id}><strong>{d.title}</strong><span>{d.platform??'Platform'} · {d.status} · qty {d.quantity}</span><form className="auth-card" onSubmit={event=>submit(event,d.id)}><label>Caption<textarea name="caption" required rows={4}/></label><label>Catatan konsep<textarea name="notes" rows={3}/></label><label>URL konten<input name="url" type="url"/></label><button className="btn-solid">Kirim versi konten</button></form></article>)}</div>:null}</section>}

const adminTransitions:CampaignStatus[]=['internal_review','changes_requested','planning','active','publishing','monitoring','reporting','completed','archived'];
export function AdminCampaignsPage(){const qc=useQueryClient();const campaigns=useQuery({queryKey:['campaigns','admin'],queryFn:getAdminCampaigns});const [message,setMessage]=useState('');async function move(id:string,to:CampaignStatus){try{await transitionCampaign(id,to,'Updated through Admin workspace');await qc.invalidateQueries({queryKey:['campaigns']});setMessage('Status campaign diperbarui.')}catch(error){setMessage(error instanceof Error?error.message:'Status gagal diperbarui.')}}return <section><p className="eyebrow">ADMIN CAMPAIGNS</p><h1>Campaign operations</h1><p className="muted">Transisi tetap divalidasi Backend state machine dan permission campaigns.manage.</p><p>{message}</p><div className="ops-list">{campaigns.data?.map(c=><article key={c.id}><strong>{c.name}</strong><span>{c.status} · organisasi {c.organization_id.slice(0,8)}</span><select defaultValue="" onChange={event=>{if(event.target.value)void move(c.id,event.target.value as CampaignStatus)}}><option value="">Ubah status</option>{adminTransitions.map(status=><option key={status} value={status}>{status}</option>)}</select></article>)}</div></section>}
